/*
 * Generated by JasperReports - 30/10/08 13:26
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;

import java.util.*;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.data.*;


/**
 *
 */
public class rpt_EtiqLibrNoAgot47 extends JRCalculator
{


    /**
     *
     */
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillParameter parameter_P1 = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;

    private JRFillField field_ANCHO = null;
    private JRFillField field_RESUMEN = null;
    private JRFillField field_AUTOR32PROLOGO = null;
    private JRFillField field_EJERCICIO = null;
    private JRFillField field_ALTO = null;
    private JRFillField field_NIVEL32DE32CLASIFICACION = null;
    private JRFillField field_AUTOR = null;
    private JRFillField field_AUTOR32PRESENTACION = null;
    private JRFillField field_MATERIA = null;
    private JRFillField field_COLABORADOR = null;
    private JRFillField field_EDITORIAL = null;
    private JRFillField field_CODIGO = null;
    private JRFillField field_TITULO = null;
    private JRFillField field_EXISTENCIAS = null;
    private JRFillField field_PAGINAS = null;

    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_GMATERIA_COUNT = null;
    private JRFillVariable variable_RESUMEN_COUNT = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
        parameter_P1 = (JRFillParameter)pm.get("P1");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
        field_ANCHO = (JRFillField)fm.get("ANCHO");
        field_RESUMEN = (JRFillField)fm.get("RESUMEN");
        field_AUTOR32PROLOGO = (JRFillField)fm.get("AUTOR PROLOGO");
        field_EJERCICIO = (JRFillField)fm.get("EJERCICIO");
        field_ALTO = (JRFillField)fm.get("ALTO");
        field_NIVEL32DE32CLASIFICACION = (JRFillField)fm.get("NIVEL DE CLASIFICACION");
        field_AUTOR = (JRFillField)fm.get("AUTOR");
        field_AUTOR32PRESENTACION = (JRFillField)fm.get("AUTOR PRESENTACION");
        field_MATERIA = (JRFillField)fm.get("MATERIA");
        field_COLABORADOR = (JRFillField)fm.get("COLABORADOR");
        field_EDITORIAL = (JRFillField)fm.get("EDITORIAL");
        field_CODIGO = (JRFillField)fm.get("CODIGO");
        field_TITULO = (JRFillField)fm.get("TITULO");
        field_EXISTENCIAS = (JRFillField)fm.get("EXISTENCIAS");
        field_PAGINAS = (JRFillField)fm.get("PAGINAS");
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
        variable_GMATERIA_COUNT = (JRFillVariable)vm.get("GMATERIA_COUNT");
        variable_RESUMEN_COUNT = (JRFillVariable)vm.get("RESUMEN_COUNT");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 124 : // 124
            {
                value = (java.lang.String)(((java.lang.String)field_COLABORADOR.getValue()));
                break;
            }
            case 106 : // 106
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 115 : // 115
            {
                value = (java.lang.Object)(((java.lang.String)field_MATERIA.getValue()));
                break;
            }
            case 114 : // 114
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 119 : // 119
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 129 : // 129
            {
                value = (java.lang.String)(((java.lang.String)field_AUTOR32PRESENTACION.getValue()));
                break;
            }
            case 131 : // 131
            {
                value = (java.lang.String)("( "+((java.lang.String)field_ANCHO.getValue())+" cm x "+((java.lang.String)field_ALTO.getValue())+" cm )");
                break;
            }
            case 110 : // 110
            {
                value = (java.lang.String)("");
                break;
            }
            case 113 : // 113
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 104 : // 104
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 127 : // 127
            {
                value = (java.lang.String)("Nivel: "+((java.lang.String)field_NIVEL32DE32CLASIFICACION.getValue()));
                break;
            }
            case 108 : // 108
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 107 : // 107
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 111 : // 111
            {
                value = (java.lang.Object)(((java.lang.String)field_MATERIA.getValue()));
                break;
            }
            case 132 : // 132
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_PAGINAS.getValue()).toUpperCase()!=null));
                break;
            }
            case 130 : // 130
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_ANCHO.getValue())+((java.lang.String)field_ALTO.getValue()).toUpperCase()!=null));
                break;
            }
            case 126 : // 126
            {
                value = (java.lang.String)("Existencias: "+((java.lang.String)field_EXISTENCIAS.getValue()));
                break;
            }
            case 118 : // 118
            {
                value = (java.lang.String)(((java.lang.String)field_RESUMEN.getValue()));
                break;
            }
            case 105 : // 105
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 125 : // 125
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_EJERCICIO.getValue()));
                break;
            }
            case 134 : // 134
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getValue()));
                break;
            }
            case 122 : // 122
            {
                value = (java.lang.String)(((java.lang.String)field_AUTOR.getValue()));
                break;
            }
            case 102 : // 102
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 116 : // 116
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_RESUMEN.getValue()).toUpperCase()!=null));
                break;
            }
            case 133 : // 133
            {
                value = (java.lang.String)(((java.lang.String)field_PAGINAS.getValue())+", ");
                break;
            }
            case 120 : // 120
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 109 : // 109
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 121 : // 121
            {
                value = (java.lang.String)("("+((java.lang.String)field_CODIGO.getValue())+")"+" "+((java.lang.String)field_TITULO.getValue()));
                break;
            }
            case 117 : // 117
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_RESUMEN.getValue()).toUpperCase()!=null));
                break;
            }
            case 123 : // 123
            {
                value = (java.lang.String)(((java.lang.String)field_EDITORIAL.getValue()));
                break;
            }
            case 128 : // 128
            {
                value = (java.lang.String)(((java.lang.String)field_AUTOR32PROLOGO.getValue()));
                break;
            }
            case 112 : // 112
            {
                value = (java.lang.String)(((java.lang.String)field_MATERIA.getValue()));
                break;
            }
            case 135 : // 135
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getValue()));
                break;
            }
            case 103 : // 103
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 124 : // 124
            {
                value = (java.lang.String)(((java.lang.String)field_COLABORADOR.getOldValue()));
                break;
            }
            case 106 : // 106
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 115 : // 115
            {
                value = (java.lang.Object)(((java.lang.String)field_MATERIA.getOldValue()));
                break;
            }
            case 114 : // 114
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 119 : // 119
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 129 : // 129
            {
                value = (java.lang.String)(((java.lang.String)field_AUTOR32PRESENTACION.getOldValue()));
                break;
            }
            case 131 : // 131
            {
                value = (java.lang.String)("( "+((java.lang.String)field_ANCHO.getOldValue())+" cm x "+((java.lang.String)field_ALTO.getOldValue())+" cm )");
                break;
            }
            case 110 : // 110
            {
                value = (java.lang.String)("");
                break;
            }
            case 113 : // 113
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 104 : // 104
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 127 : // 127
            {
                value = (java.lang.String)("Nivel: "+((java.lang.String)field_NIVEL32DE32CLASIFICACION.getOldValue()));
                break;
            }
            case 108 : // 108
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 107 : // 107
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 111 : // 111
            {
                value = (java.lang.Object)(((java.lang.String)field_MATERIA.getOldValue()));
                break;
            }
            case 132 : // 132
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_PAGINAS.getOldValue()).toUpperCase()!=null));
                break;
            }
            case 130 : // 130
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_ANCHO.getOldValue())+((java.lang.String)field_ALTO.getOldValue()).toUpperCase()!=null));
                break;
            }
            case 126 : // 126
            {
                value = (java.lang.String)("Existencias: "+((java.lang.String)field_EXISTENCIAS.getOldValue()));
                break;
            }
            case 118 : // 118
            {
                value = (java.lang.String)(((java.lang.String)field_RESUMEN.getOldValue()));
                break;
            }
            case 105 : // 105
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 125 : // 125
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_EJERCICIO.getOldValue()));
                break;
            }
            case 134 : // 134
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()));
                break;
            }
            case 122 : // 122
            {
                value = (java.lang.String)(((java.lang.String)field_AUTOR.getOldValue()));
                break;
            }
            case 102 : // 102
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 116 : // 116
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_RESUMEN.getOldValue()).toUpperCase()!=null));
                break;
            }
            case 133 : // 133
            {
                value = (java.lang.String)(((java.lang.String)field_PAGINAS.getOldValue())+", ");
                break;
            }
            case 120 : // 120
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 109 : // 109
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 121 : // 121
            {
                value = (java.lang.String)("("+((java.lang.String)field_CODIGO.getOldValue())+")"+" "+((java.lang.String)field_TITULO.getOldValue()));
                break;
            }
            case 117 : // 117
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_RESUMEN.getOldValue()).toUpperCase()!=null));
                break;
            }
            case 123 : // 123
            {
                value = (java.lang.String)(((java.lang.String)field_EDITORIAL.getOldValue()));
                break;
            }
            case 128 : // 128
            {
                value = (java.lang.String)(((java.lang.String)field_AUTOR32PROLOGO.getOldValue()));
                break;
            }
            case 112 : // 112
            {
                value = (java.lang.String)(((java.lang.String)field_MATERIA.getOldValue()));
                break;
            }
            case 135 : // 135
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()));
                break;
            }
            case 103 : // 103
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 124 : // 124
            {
                value = (java.lang.String)(((java.lang.String)field_COLABORADOR.getValue()));
                break;
            }
            case 106 : // 106
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 115 : // 115
            {
                value = (java.lang.Object)(((java.lang.String)field_MATERIA.getValue()));
                break;
            }
            case 114 : // 114
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 119 : // 119
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 129 : // 129
            {
                value = (java.lang.String)(((java.lang.String)field_AUTOR32PRESENTACION.getValue()));
                break;
            }
            case 131 : // 131
            {
                value = (java.lang.String)("( "+((java.lang.String)field_ANCHO.getValue())+" cm x "+((java.lang.String)field_ALTO.getValue())+" cm )");
                break;
            }
            case 110 : // 110
            {
                value = (java.lang.String)("");
                break;
            }
            case 113 : // 113
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 104 : // 104
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 127 : // 127
            {
                value = (java.lang.String)("Nivel: "+((java.lang.String)field_NIVEL32DE32CLASIFICACION.getValue()));
                break;
            }
            case 108 : // 108
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 107 : // 107
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 111 : // 111
            {
                value = (java.lang.Object)(((java.lang.String)field_MATERIA.getValue()));
                break;
            }
            case 132 : // 132
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_PAGINAS.getValue()).toUpperCase()!=null));
                break;
            }
            case 130 : // 130
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_ANCHO.getValue())+((java.lang.String)field_ALTO.getValue()).toUpperCase()!=null));
                break;
            }
            case 126 : // 126
            {
                value = (java.lang.String)("Existencias: "+((java.lang.String)field_EXISTENCIAS.getValue()));
                break;
            }
            case 118 : // 118
            {
                value = (java.lang.String)(((java.lang.String)field_RESUMEN.getValue()));
                break;
            }
            case 105 : // 105
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 125 : // 125
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_EJERCICIO.getValue()));
                break;
            }
            case 134 : // 134
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()));
                break;
            }
            case 122 : // 122
            {
                value = (java.lang.String)(((java.lang.String)field_AUTOR.getValue()));
                break;
            }
            case 102 : // 102
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 116 : // 116
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_RESUMEN.getValue()).toUpperCase()!=null));
                break;
            }
            case 133 : // 133
            {
                value = (java.lang.String)(((java.lang.String)field_PAGINAS.getValue())+", ");
                break;
            }
            case 120 : // 120
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 109 : // 109
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 121 : // 121
            {
                value = (java.lang.String)("("+((java.lang.String)field_CODIGO.getValue())+")"+" "+((java.lang.String)field_TITULO.getValue()));
                break;
            }
            case 117 : // 117
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_RESUMEN.getValue()).toUpperCase()!=null));
                break;
            }
            case 123 : // 123
            {
                value = (java.lang.String)(((java.lang.String)field_EDITORIAL.getValue()));
                break;
            }
            case 128 : // 128
            {
                value = (java.lang.String)(((java.lang.String)field_AUTOR32PROLOGO.getValue()));
                break;
            }
            case 112 : // 112
            {
                value = (java.lang.String)(((java.lang.String)field_MATERIA.getValue()));
                break;
            }
            case 135 : // 135
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()));
                break;
            }
            case 103 : // 103
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
