/*
 * Generated by JasperReports - 14/12/05 10:16
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;

import java.util.*;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.data.*;


/**
 *
 */
public class RPT_59 extends JRCalculator
{


    /**
     *
     */
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillParameter parameter_P1 = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_P2 = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillParameter parameter_P3 = null;
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;

    private JRFillField field_TIPOACTO = null;
    private JRFillField field_NOMBRE32ARTÍSTICO = null;
    private JRFillField field_LOCALIDAD = null;
    private JRFillField field_OFERENTE = null;
    private JRFillField field_FECHA = null;
    private JRFillField field_OBSERVACIONES = null;
    private JRFillField field_DNI = null;
    private JRFillField field_FAX = null;
    private JRFillField field_IMPORTE = null;
    private JRFillField field_EMAIL = null;
    private JRFillField field_CONTACTO = null;
    private JRFillField field_DOMICILIO = null;
    private JRFillField field_TELÉFONO322 = null;
    private JRFillField field_TELÉFONO321 = null;
    private JRFillField field_OFRECIMIENTO = null;
    private JRFillField field_Nº32REGISTRO = null;
    private JRFillField field_CÓDIGO32POSTAL = null;
    private JRFillField field_PROVINCIA = null;
    private JRFillField field_MODALIDAD32ACTO = null;
    private JRFillField field_DS_ESTADO = null;

    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_OFERENTE_COUNT = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
        parameter_P1 = (JRFillParameter)pm.get("P1");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_P2 = (JRFillParameter)pm.get("P2");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
        parameter_P3 = (JRFillParameter)pm.get("P3");
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
        field_TIPOACTO = (JRFillField)fm.get("TIPOACTO");
        field_NOMBRE32ARTÍSTICO = (JRFillField)fm.get("NOMBRE ARTÍSTICO");
        field_LOCALIDAD = (JRFillField)fm.get("LOCALIDAD");
        field_OFERENTE = (JRFillField)fm.get("OFERENTE");
        field_FECHA = (JRFillField)fm.get("FECHA");
        field_OBSERVACIONES = (JRFillField)fm.get("OBSERVACIONES");
        field_DNI = (JRFillField)fm.get("DNI");
        field_FAX = (JRFillField)fm.get("FAX");
        field_IMPORTE = (JRFillField)fm.get("IMPORTE");
        field_EMAIL = (JRFillField)fm.get("EMAIL");
        field_CONTACTO = (JRFillField)fm.get("CONTACTO");
        field_DOMICILIO = (JRFillField)fm.get("DOMICILIO");
        field_TELÉFONO322 = (JRFillField)fm.get("TELÉFONO 2");
        field_TELÉFONO321 = (JRFillField)fm.get("TELÉFONO 1");
        field_OFRECIMIENTO = (JRFillField)fm.get("OFRECIMIENTO");
        field_Nº32REGISTRO = (JRFillField)fm.get("Nº REGISTRO");
        field_CÓDIGO32POSTAL = (JRFillField)fm.get("CÓDIGO POSTAL");
        field_PROVINCIA = (JRFillField)fm.get("PROVINCIA");
        field_MODALIDAD32ACTO = (JRFillField)fm.get("MODALIDAD ACTO");
        field_DS_ESTADO = (JRFillField)fm.get("DS_ESTADO");
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
        variable_OFERENTE_COUNT = (JRFillVariable)vm.get("OFERENTE_COUNT");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 149 : // 149
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 155 : // 155
            {
                value = (java.lang.Object)(((java.lang.String)field_OFERENTE.getValue()));
                break;
            }
            case 157 : // 157
            {
                value = (java.lang.String)(((java.lang.String)field_DNI.getValue()));
                break;
            }
            case 172 : // 172
            {
                value = (java.lang.String)(((java.lang.String)field_OBSERVACIONES.getValue()));
                break;
            }
            case 156 : // 156
            {
                value = (java.lang.String)(((java.lang.String)field_OFERENTE.getValue()));
                break;
            }
            case 159 : // 159
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_CÓDIGO32POSTAL.getValue()));
                break;
            }
            case 178 : // 178
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getValue()));
                break;
            }
            case 169 : // 169
            {
                value = (java.lang.String)(((java.lang.String)field_OFRECIMIENTO.getValue()));
                break;
            }
            case 177 : // 177
            {
                value = (java.lang.String)(java.util.Calendar.getInstance().get(java.util.Calendar.DATE)
+ "/" +
((java.util.Calendar.getInstance().get(java.util.Calendar.MONTH))+1)
+ "/" +
java.util.Calendar.getInstance().get(java.util.Calendar.YEAR));
                break;
            }
            case 165 : // 165
            {
                value = (java.lang.String)(((java.lang.String)field_EMAIL.getValue()));
                break;
            }
            case 168 : // 168
            {
                value = (java.lang.String)(((java.lang.String)field_FECHA.getValue()));
                break;
            }
            case 147 : // 147
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 151 : // 151
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 148 : // 148
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 145 : // 145
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 152 : // 152
            {
                value = (java.lang.String)("MUS");
                break;
            }
            case 166 : // 166
            {
                value = (java.lang.String)(((java.lang.String)field_CONTACTO.getValue()));
                break;
            }
            case 174 : // 174
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 173 : // 173
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 144 : // 144
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 163 : // 163
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_TELÉFONO322.getValue()));
                break;
            }
            case 167 : // 167
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_Nº32REGISTRO.getValue()));
                break;
            }
            case 146 : // 146
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 161 : // 161
            {
                value = (java.lang.String)(((java.lang.String)field_PROVINCIA.getValue()));
                break;
            }
            case 164 : // 164
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_FAX.getValue()));
                break;
            }
            case 154 : // 154
            {
                value = (java.lang.String)("DN");
                break;
            }
            case 170 : // 170
            {
                value = (java.lang.String)(((java.lang.String)field_NOMBRE32ARTÍSTICO.getValue()));
                break;
            }
            case 162 : // 162
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_TELÉFONO321.getValue()));
                break;
            }
            case 171 : // 171
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_IMPORTE.getValue()));
                break;
            }
            case 179 : // 179
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getValue()));
                break;
            }
            case 153 : // 153
            {
                value = (java.lang.String)("CLA");
                break;
            }
            case 176 : // 176
            {
                value = (java.lang.String)("de tipo "+((java.lang.String)field_TIPOACTO.getValue())+" y modalidad "+((java.lang.String)field_MODALIDAD32ACTO.getValue())+", con estado "+((java.lang.String)field_DS_ESTADO.getValue()));
                break;
            }
            case 158 : // 158
            {
                value = (java.lang.String)(((java.lang.String)field_DOMICILIO.getValue()));
                break;
            }
            case 175 : // 175
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_OFERENTE.getValue()).toUpperCase()!=null));
                break;
            }
            case 150 : // 150
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 160 : // 160
            {
                value = (java.lang.String)(((java.lang.String)field_LOCALIDAD.getValue()));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 149 : // 149
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 155 : // 155
            {
                value = (java.lang.Object)(((java.lang.String)field_OFERENTE.getOldValue()));
                break;
            }
            case 157 : // 157
            {
                value = (java.lang.String)(((java.lang.String)field_DNI.getOldValue()));
                break;
            }
            case 172 : // 172
            {
                value = (java.lang.String)(((java.lang.String)field_OBSERVACIONES.getOldValue()));
                break;
            }
            case 156 : // 156
            {
                value = (java.lang.String)(((java.lang.String)field_OFERENTE.getOldValue()));
                break;
            }
            case 159 : // 159
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_CÓDIGO32POSTAL.getOldValue()));
                break;
            }
            case 178 : // 178
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()));
                break;
            }
            case 169 : // 169
            {
                value = (java.lang.String)(((java.lang.String)field_OFRECIMIENTO.getOldValue()));
                break;
            }
            case 177 : // 177
            {
                value = (java.lang.String)(java.util.Calendar.getInstance().get(java.util.Calendar.DATE)
+ "/" +
((java.util.Calendar.getInstance().get(java.util.Calendar.MONTH))+1)
+ "/" +
java.util.Calendar.getInstance().get(java.util.Calendar.YEAR));
                break;
            }
            case 165 : // 165
            {
                value = (java.lang.String)(((java.lang.String)field_EMAIL.getOldValue()));
                break;
            }
            case 168 : // 168
            {
                value = (java.lang.String)(((java.lang.String)field_FECHA.getOldValue()));
                break;
            }
            case 147 : // 147
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 151 : // 151
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 148 : // 148
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 145 : // 145
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 152 : // 152
            {
                value = (java.lang.String)("MUS");
                break;
            }
            case 166 : // 166
            {
                value = (java.lang.String)(((java.lang.String)field_CONTACTO.getOldValue()));
                break;
            }
            case 174 : // 174
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 173 : // 173
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 144 : // 144
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 163 : // 163
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_TELÉFONO322.getOldValue()));
                break;
            }
            case 167 : // 167
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_Nº32REGISTRO.getOldValue()));
                break;
            }
            case 146 : // 146
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 161 : // 161
            {
                value = (java.lang.String)(((java.lang.String)field_PROVINCIA.getOldValue()));
                break;
            }
            case 164 : // 164
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_FAX.getOldValue()));
                break;
            }
            case 154 : // 154
            {
                value = (java.lang.String)("DN");
                break;
            }
            case 170 : // 170
            {
                value = (java.lang.String)(((java.lang.String)field_NOMBRE32ARTÍSTICO.getOldValue()));
                break;
            }
            case 162 : // 162
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_TELÉFONO321.getOldValue()));
                break;
            }
            case 171 : // 171
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_IMPORTE.getOldValue()));
                break;
            }
            case 179 : // 179
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()));
                break;
            }
            case 153 : // 153
            {
                value = (java.lang.String)("CLA");
                break;
            }
            case 176 : // 176
            {
                value = (java.lang.String)("de tipo "+((java.lang.String)field_TIPOACTO.getOldValue())+" y modalidad "+((java.lang.String)field_MODALIDAD32ACTO.getOldValue())+", con estado "+((java.lang.String)field_DS_ESTADO.getOldValue()));
                break;
            }
            case 158 : // 158
            {
                value = (java.lang.String)(((java.lang.String)field_DOMICILIO.getOldValue()));
                break;
            }
            case 175 : // 175
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_OFERENTE.getOldValue()).toUpperCase()!=null));
                break;
            }
            case 150 : // 150
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 160 : // 160
            {
                value = (java.lang.String)(((java.lang.String)field_LOCALIDAD.getOldValue()));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 149 : // 149
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 155 : // 155
            {
                value = (java.lang.Object)(((java.lang.String)field_OFERENTE.getValue()));
                break;
            }
            case 157 : // 157
            {
                value = (java.lang.String)(((java.lang.String)field_DNI.getValue()));
                break;
            }
            case 172 : // 172
            {
                value = (java.lang.String)(((java.lang.String)field_OBSERVACIONES.getValue()));
                break;
            }
            case 156 : // 156
            {
                value = (java.lang.String)(((java.lang.String)field_OFERENTE.getValue()));
                break;
            }
            case 159 : // 159
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_CÓDIGO32POSTAL.getValue()));
                break;
            }
            case 178 : // 178
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()));
                break;
            }
            case 169 : // 169
            {
                value = (java.lang.String)(((java.lang.String)field_OFRECIMIENTO.getValue()));
                break;
            }
            case 177 : // 177
            {
                value = (java.lang.String)(java.util.Calendar.getInstance().get(java.util.Calendar.DATE)
+ "/" +
((java.util.Calendar.getInstance().get(java.util.Calendar.MONTH))+1)
+ "/" +
java.util.Calendar.getInstance().get(java.util.Calendar.YEAR));
                break;
            }
            case 165 : // 165
            {
                value = (java.lang.String)(((java.lang.String)field_EMAIL.getValue()));
                break;
            }
            case 168 : // 168
            {
                value = (java.lang.String)(((java.lang.String)field_FECHA.getValue()));
                break;
            }
            case 147 : // 147
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 151 : // 151
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 148 : // 148
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 145 : // 145
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 152 : // 152
            {
                value = (java.lang.String)("MUS");
                break;
            }
            case 166 : // 166
            {
                value = (java.lang.String)(((java.lang.String)field_CONTACTO.getValue()));
                break;
            }
            case 174 : // 174
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 173 : // 173
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 144 : // 144
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 163 : // 163
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_TELÉFONO322.getValue()));
                break;
            }
            case 167 : // 167
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_Nº32REGISTRO.getValue()));
                break;
            }
            case 146 : // 146
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 161 : // 161
            {
                value = (java.lang.String)(((java.lang.String)field_PROVINCIA.getValue()));
                break;
            }
            case 164 : // 164
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_FAX.getValue()));
                break;
            }
            case 154 : // 154
            {
                value = (java.lang.String)("DN");
                break;
            }
            case 170 : // 170
            {
                value = (java.lang.String)(((java.lang.String)field_NOMBRE32ARTÍSTICO.getValue()));
                break;
            }
            case 162 : // 162
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_TELÉFONO321.getValue()));
                break;
            }
            case 171 : // 171
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_IMPORTE.getValue()));
                break;
            }
            case 179 : // 179
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()));
                break;
            }
            case 153 : // 153
            {
                value = (java.lang.String)("CLA");
                break;
            }
            case 176 : // 176
            {
                value = (java.lang.String)("de tipo "+((java.lang.String)field_TIPOACTO.getValue())+" y modalidad "+((java.lang.String)field_MODALIDAD32ACTO.getValue())+", con estado "+((java.lang.String)field_DS_ESTADO.getValue()));
                break;
            }
            case 158 : // 158
            {
                value = (java.lang.String)(((java.lang.String)field_DOMICILIO.getValue()));
                break;
            }
            case 175 : // 175
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_OFERENTE.getValue()).toUpperCase()!=null));
                break;
            }
            case 150 : // 150
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 160 : // 160
            {
                value = (java.lang.String)(((java.lang.String)field_LOCALIDAD.getValue()));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
