/*
 * Generated by JasperReports - 25/09/08 13:17
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;

import java.util.*;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.data.*;


/**
 *
 */
public class rpt_ListMovDiario53 extends JRCalculator
{


    /**
     *
     */
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillParameter parameter_P1 = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_P2 = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillParameter parameter_P3 = null;
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;

    private JRFillField field_SAL = null;
    private JRFillField field_INI = null;
    private JRFillField field_FECHA = null;
    private JRFillField field_OBSERVACIONES = null;
    private JRFillField field_DIA = null;
    private JRFillField field_CANTIDAD = null;
    private JRFillField field_EJERCICIO = null;
    private JRFillField field_DS_OFICINA = null;
    private JRFillField field_OFICINA = null;
    private JRFillField field_DIAS = null;
    private JRFillField field_MES = null;
    private JRFillField field_MOVIMIENTO = null;
    private JRFillField field_CODIGO = null;
    private JRFillField field_TITULO = null;

    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_ENTRADAS = null;
    private JRFillVariable variable_SALIDAS = null;
    private JRFillVariable variable_TOTSALIDAS = null;
    private JRFillVariable variable_TOTENTRADAS = null;
    private JRFillVariable variable_GFECHA_COUNT = null;
    private JRFillVariable variable_CODIGO_COUNT = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
        parameter_P1 = (JRFillParameter)pm.get("P1");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_P2 = (JRFillParameter)pm.get("P2");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
        parameter_P3 = (JRFillParameter)pm.get("P3");
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
        field_SAL = (JRFillField)fm.get("SAL");
        field_INI = (JRFillField)fm.get("INI");
        field_FECHA = (JRFillField)fm.get("FECHA");
        field_OBSERVACIONES = (JRFillField)fm.get("OBSERVACIONES");
        field_DIA = (JRFillField)fm.get("DIA");
        field_CANTIDAD = (JRFillField)fm.get("CANTIDAD");
        field_EJERCICIO = (JRFillField)fm.get("EJERCICIO");
        field_DS_OFICINA = (JRFillField)fm.get("DS_OFICINA");
        field_OFICINA = (JRFillField)fm.get("OFICINA");
        field_DIAS = (JRFillField)fm.get("DIAS");
        field_MES = (JRFillField)fm.get("MES");
        field_MOVIMIENTO = (JRFillField)fm.get("MOVIMIENTO");
        field_CODIGO = (JRFillField)fm.get("CODIGO");
        field_TITULO = (JRFillField)fm.get("TITULO");
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
        variable_ENTRADAS = (JRFillVariable)vm.get("ENTRADAS");
        variable_SALIDAS = (JRFillVariable)vm.get("SALIDAS");
        variable_TOTSALIDAS = (JRFillVariable)vm.get("TOTSALIDAS");
        variable_TOTENTRADAS = (JRFillVariable)vm.get("TOTENTRADAS");
        variable_GFECHA_COUNT = (JRFillVariable)vm.get("GFECHA_COUNT");
        variable_CODIGO_COUNT = (JRFillVariable)vm.get("CODIGO_COUNT");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : // 0
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 15 : // 15
            {
                value = (java.lang.Object)(((java.lang.String)field_FECHA.getValue()));
                break;
            }
            case 22 : // 22
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 5 : // 5
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 7 : // 7
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 29 : // 29
            {
                value = (java.lang.String)(((java.lang.String)field_SAL.getValue()));
                break;
            }
            case 23 : // 23
            {
                value = (java.lang.String)(((java.lang.String)field_CODIGO.getValue()));
                break;
            }
            case 9 : // 9
            {
                value = (java.lang.String)("01/01/2050");
                break;
            }
            case 14 : // 14
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_ENTRADAS.getValue()));
                break;
            }
            case 21 : // 21
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 24 : // 24
            {
                value = (java.lang.String)(((java.lang.String)field_TITULO.getValue()));
                break;
            }
            case 4 : // 4
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3 : // 3
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 10 : // 10
            {
                value = (java.lang.String)(null);
                break;
            }
            case 18 : // 18
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 26 : // 26
            {
                value = (java.lang.String)(((java.lang.String)field_DS_OFICINA.getValue()));
                break;
            }
            case 1 : // 1
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 19 : // 19
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 20 : // 20
            {
                value = (java.lang.Object)(((java.lang.String)field_CODIGO.getValue()));
                break;
            }
            case 30 : // 30
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getValue()));
                break;
            }
            case 12 : // 12
            {
                value = (java.lang.Integer)((((java.lang.String)field_MOVIMIENTO.getValue()).toUpperCase().equals("1"))?(new Integer(0)):(new Integer(((java.lang.String)field_CANTIDAD.getValue()))));
                break;
            }
            case 16 : // 16
            {
                value = (java.lang.String)("MOVIMIENTOS DIARIOS  - ");
                break;
            }
            case 31 : // 31
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getValue()));
                break;
            }
            case 2 : // 2
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 13 : // 13
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_SALIDAS.getValue()));
                break;
            }
            case 6 : // 6
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 11 : // 11
            {
                value = (java.lang.Integer)((((java.lang.String)field_MOVIMIENTO.getValue()).toUpperCase().equals("0"))?(new Integer(0)):(new Integer(((java.lang.String)field_CANTIDAD.getValue()))));
                break;
            }
            case 27 : // 27
            {
                value = (java.lang.String)(((java.lang.String)field_INI.getValue()));
                break;
            }
            case 32 : // 32
            {
                value = (java.lang.String)(java.util.Calendar.getInstance().get(java.util.Calendar.DATE)
+ "/" +
((java.util.Calendar.getInstance().get(java.util.Calendar.MONTH))+1)
+ "/" +
java.util.Calendar.getInstance().get(java.util.Calendar.YEAR));
                break;
            }
            case 28 : // 28
            {
                value = (java.lang.String)(((java.lang.String)field_CANTIDAD.getValue()));
                break;
            }
            case 25 : // 25
            {
                value = (java.lang.String)(((java.lang.String)field_OBSERVACIONES.getValue()));
                break;
            }
            case 17 : // 17
            {
                value = (java.lang.String)(((java.lang.String)field_DIAS.getValue()));
                break;
            }
            case 8 : // 8
            {
                value = (java.lang.String)("01/01/1950");
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : // 0
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 15 : // 15
            {
                value = (java.lang.Object)(((java.lang.String)field_FECHA.getOldValue()));
                break;
            }
            case 22 : // 22
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 5 : // 5
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 7 : // 7
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 29 : // 29
            {
                value = (java.lang.String)(((java.lang.String)field_SAL.getOldValue()));
                break;
            }
            case 23 : // 23
            {
                value = (java.lang.String)(((java.lang.String)field_CODIGO.getOldValue()));
                break;
            }
            case 9 : // 9
            {
                value = (java.lang.String)("01/01/2050");
                break;
            }
            case 14 : // 14
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_ENTRADAS.getOldValue()));
                break;
            }
            case 21 : // 21
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 24 : // 24
            {
                value = (java.lang.String)(((java.lang.String)field_TITULO.getOldValue()));
                break;
            }
            case 4 : // 4
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3 : // 3
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 10 : // 10
            {
                value = (java.lang.String)(null);
                break;
            }
            case 18 : // 18
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 26 : // 26
            {
                value = (java.lang.String)(((java.lang.String)field_DS_OFICINA.getOldValue()));
                break;
            }
            case 1 : // 1
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 19 : // 19
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 20 : // 20
            {
                value = (java.lang.Object)(((java.lang.String)field_CODIGO.getOldValue()));
                break;
            }
            case 30 : // 30
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()));
                break;
            }
            case 12 : // 12
            {
                value = (java.lang.Integer)((((java.lang.String)field_MOVIMIENTO.getOldValue()).toUpperCase().equals("1"))?(new Integer(0)):(new Integer(((java.lang.String)field_CANTIDAD.getOldValue()))));
                break;
            }
            case 16 : // 16
            {
                value = (java.lang.String)("MOVIMIENTOS DIARIOS  - ");
                break;
            }
            case 31 : // 31
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()));
                break;
            }
            case 2 : // 2
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 13 : // 13
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_SALIDAS.getOldValue()));
                break;
            }
            case 6 : // 6
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 11 : // 11
            {
                value = (java.lang.Integer)((((java.lang.String)field_MOVIMIENTO.getOldValue()).toUpperCase().equals("0"))?(new Integer(0)):(new Integer(((java.lang.String)field_CANTIDAD.getOldValue()))));
                break;
            }
            case 27 : // 27
            {
                value = (java.lang.String)(((java.lang.String)field_INI.getOldValue()));
                break;
            }
            case 32 : // 32
            {
                value = (java.lang.String)(java.util.Calendar.getInstance().get(java.util.Calendar.DATE)
+ "/" +
((java.util.Calendar.getInstance().get(java.util.Calendar.MONTH))+1)
+ "/" +
java.util.Calendar.getInstance().get(java.util.Calendar.YEAR));
                break;
            }
            case 28 : // 28
            {
                value = (java.lang.String)(((java.lang.String)field_CANTIDAD.getOldValue()));
                break;
            }
            case 25 : // 25
            {
                value = (java.lang.String)(((java.lang.String)field_OBSERVACIONES.getOldValue()));
                break;
            }
            case 17 : // 17
            {
                value = (java.lang.String)(((java.lang.String)field_DIAS.getOldValue()));
                break;
            }
            case 8 : // 8
            {
                value = (java.lang.String)("01/01/1950");
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : // 0
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 15 : // 15
            {
                value = (java.lang.Object)(((java.lang.String)field_FECHA.getValue()));
                break;
            }
            case 22 : // 22
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 5 : // 5
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 7 : // 7
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 29 : // 29
            {
                value = (java.lang.String)(((java.lang.String)field_SAL.getValue()));
                break;
            }
            case 23 : // 23
            {
                value = (java.lang.String)(((java.lang.String)field_CODIGO.getValue()));
                break;
            }
            case 9 : // 9
            {
                value = (java.lang.String)("01/01/2050");
                break;
            }
            case 14 : // 14
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_ENTRADAS.getEstimatedValue()));
                break;
            }
            case 21 : // 21
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 24 : // 24
            {
                value = (java.lang.String)(((java.lang.String)field_TITULO.getValue()));
                break;
            }
            case 4 : // 4
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3 : // 3
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 10 : // 10
            {
                value = (java.lang.String)(null);
                break;
            }
            case 18 : // 18
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 26 : // 26
            {
                value = (java.lang.String)(((java.lang.String)field_DS_OFICINA.getValue()));
                break;
            }
            case 1 : // 1
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 19 : // 19
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 20 : // 20
            {
                value = (java.lang.Object)(((java.lang.String)field_CODIGO.getValue()));
                break;
            }
            case 30 : // 30
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()));
                break;
            }
            case 12 : // 12
            {
                value = (java.lang.Integer)((((java.lang.String)field_MOVIMIENTO.getValue()).toUpperCase().equals("1"))?(new Integer(0)):(new Integer(((java.lang.String)field_CANTIDAD.getValue()))));
                break;
            }
            case 16 : // 16
            {
                value = (java.lang.String)("MOVIMIENTOS DIARIOS  - ");
                break;
            }
            case 31 : // 31
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()));
                break;
            }
            case 2 : // 2
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 13 : // 13
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_SALIDAS.getEstimatedValue()));
                break;
            }
            case 6 : // 6
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 11 : // 11
            {
                value = (java.lang.Integer)((((java.lang.String)field_MOVIMIENTO.getValue()).toUpperCase().equals("0"))?(new Integer(0)):(new Integer(((java.lang.String)field_CANTIDAD.getValue()))));
                break;
            }
            case 27 : // 27
            {
                value = (java.lang.String)(((java.lang.String)field_INI.getValue()));
                break;
            }
            case 32 : // 32
            {
                value = (java.lang.String)(java.util.Calendar.getInstance().get(java.util.Calendar.DATE)
+ "/" +
((java.util.Calendar.getInstance().get(java.util.Calendar.MONTH))+1)
+ "/" +
java.util.Calendar.getInstance().get(java.util.Calendar.YEAR));
                break;
            }
            case 28 : // 28
            {
                value = (java.lang.String)(((java.lang.String)field_CANTIDAD.getValue()));
                break;
            }
            case 25 : // 25
            {
                value = (java.lang.String)(((java.lang.String)field_OBSERVACIONES.getValue()));
                break;
            }
            case 17 : // 17
            {
                value = (java.lang.String)(((java.lang.String)field_DIAS.getValue()));
                break;
            }
            case 8 : // 8
            {
                value = (java.lang.String)("01/01/1950");
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
