/*
 * Generated by JasperReports - 17/07/08 10:49
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;

import java.util.*;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.data.*;


/**
 *
 */
public class RPT_998_DESGLOSE extends JRCalculator
{


    /**
     *
     */
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillParameter parameter_P4 = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_P1 = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_P2 = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillParameter parameter_P3 = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;

    private JRFillField field_CD_ELEMENTO_02 = null;
    private JRFillField field_DS_ELEMENTO_04 = null;
    private JRFillField field_CD_ELEMENTO_05 = null;
    private JRFillField field_CD_TIPOELEMENTO_02 = null;
    private JRFillField field_CD_TIPOELEMENTO_05 = null;
    private JRFillField field_DS_ELEMENTO_01 = null;
    private JRFillField field_IMP_INVERSION = null;
    private JRFillField field_IMP_MANTENIMIENTO = null;
    private JRFillField field_CD_ELEMENTO_03 = null;
    private JRFillField field_DS_ELEMENTO_06 = null;
    private JRFillField field_CD_TIPOELEMENTO_01 = null;
    private JRFillField field_CD_ELEMENTO_04 = null;
    private JRFillField field_CD_TIPOELEMENTO_04 = null;
    private JRFillField field_DS_ELEMENTO_02 = null;
    private JRFillField field_IMP_TOTAL = null;
    private JRFillField field_DS_ELEMENTO_05 = null;
    private JRFillField field_CD_TIPOELEMENTO_03 = null;
    private JRFillField field_CD_ELEMENTO_01 = null;
    private JRFillField field_CD_ELEMENTO_06 = null;
    private JRFillField field_DS_ELEMENTO_03 = null;
    private JRFillField field_CD_TIPOELEMENTO_06 = null;

    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_IMP_TOTAL_01 = null;
    private JRFillVariable variable_IMP_TOTAL_02 = null;
    private JRFillVariable variable_IMP_TOTAL_03 = null;
    private JRFillVariable variable_IMP_TOTAL_04 = null;
    private JRFillVariable variable_IMP_TOTAL_05 = null;
    private JRFillVariable variable_IMP_MANTENIMIENTO_01 = null;
    private JRFillVariable variable_IMP_MANTENIMIENTO_02 = null;
    private JRFillVariable variable_IMP_MANTENIMIENTO_03 = null;
    private JRFillVariable variable_IMP_MANTENIMIENTO_04 = null;
    private JRFillVariable variable_IMP_MANTENIMIENTO_05 = null;
    private JRFillVariable variable_IMP_INVERSION_01 = null;
    private JRFillVariable variable_IMP_INVERSION_02 = null;
    private JRFillVariable variable_IMP_INVERSION_03 = null;
    private JRFillVariable variable_IMP_INVERSION_04 = null;
    private JRFillVariable variable_IMP_INVERSION_05 = null;
    private JRFillVariable variable_IMP_MANTENIMIENTO_TOTAL = null;
    private JRFillVariable variable_IMP_INVERSION_TOTAL = null;
    private JRFillVariable variable_IMP_TOTAL_TOTAL = null;
    private JRFillVariable variable_Resultado_Final_COUNT = null;
    private JRFillVariable variable_Grupo_Compañia_COUNT = null;
    private JRFillVariable variable_Grupo_Area_COUNT = null;
    private JRFillVariable variable_Grupo_Programa_COUNT = null;
    private JRFillVariable variable_Grupo_Subprograma_COUNT = null;
    private JRFillVariable variable_Grupo_Espacio_COUNT = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
        parameter_P4 = (JRFillParameter)pm.get("P4");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_P1 = (JRFillParameter)pm.get("P1");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_P2 = (JRFillParameter)pm.get("P2");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
        parameter_P3 = (JRFillParameter)pm.get("P3");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
        field_CD_ELEMENTO_02 = (JRFillField)fm.get("CD_ELEMENTO_02");
        field_DS_ELEMENTO_04 = (JRFillField)fm.get("DS_ELEMENTO_04");
        field_CD_ELEMENTO_05 = (JRFillField)fm.get("CD_ELEMENTO_05");
        field_CD_TIPOELEMENTO_02 = (JRFillField)fm.get("CD_TIPOELEMENTO_02");
        field_CD_TIPOELEMENTO_05 = (JRFillField)fm.get("CD_TIPOELEMENTO_05");
        field_DS_ELEMENTO_01 = (JRFillField)fm.get("DS_ELEMENTO_01");
        field_IMP_INVERSION = (JRFillField)fm.get("IMP_INVERSION");
        field_IMP_MANTENIMIENTO = (JRFillField)fm.get("IMP_MANTENIMIENTO");
        field_CD_ELEMENTO_03 = (JRFillField)fm.get("CD_ELEMENTO_03");
        field_DS_ELEMENTO_06 = (JRFillField)fm.get("DS_ELEMENTO_06");
        field_CD_TIPOELEMENTO_01 = (JRFillField)fm.get("CD_TIPOELEMENTO_01");
        field_CD_ELEMENTO_04 = (JRFillField)fm.get("CD_ELEMENTO_04");
        field_CD_TIPOELEMENTO_04 = (JRFillField)fm.get("CD_TIPOELEMENTO_04");
        field_DS_ELEMENTO_02 = (JRFillField)fm.get("DS_ELEMENTO_02");
        field_IMP_TOTAL = (JRFillField)fm.get("IMP_TOTAL");
        field_DS_ELEMENTO_05 = (JRFillField)fm.get("DS_ELEMENTO_05");
        field_CD_TIPOELEMENTO_03 = (JRFillField)fm.get("CD_TIPOELEMENTO_03");
        field_CD_ELEMENTO_01 = (JRFillField)fm.get("CD_ELEMENTO_01");
        field_CD_ELEMENTO_06 = (JRFillField)fm.get("CD_ELEMENTO_06");
        field_DS_ELEMENTO_03 = (JRFillField)fm.get("DS_ELEMENTO_03");
        field_CD_TIPOELEMENTO_06 = (JRFillField)fm.get("CD_TIPOELEMENTO_06");
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
        variable_IMP_TOTAL_01 = (JRFillVariable)vm.get("IMP_TOTAL_01");
        variable_IMP_TOTAL_02 = (JRFillVariable)vm.get("IMP_TOTAL_02");
        variable_IMP_TOTAL_03 = (JRFillVariable)vm.get("IMP_TOTAL_03");
        variable_IMP_TOTAL_04 = (JRFillVariable)vm.get("IMP_TOTAL_04");
        variable_IMP_TOTAL_05 = (JRFillVariable)vm.get("IMP_TOTAL_05");
        variable_IMP_MANTENIMIENTO_01 = (JRFillVariable)vm.get("IMP_MANTENIMIENTO_01");
        variable_IMP_MANTENIMIENTO_02 = (JRFillVariable)vm.get("IMP_MANTENIMIENTO_02");
        variable_IMP_MANTENIMIENTO_03 = (JRFillVariable)vm.get("IMP_MANTENIMIENTO_03");
        variable_IMP_MANTENIMIENTO_04 = (JRFillVariable)vm.get("IMP_MANTENIMIENTO_04");
        variable_IMP_MANTENIMIENTO_05 = (JRFillVariable)vm.get("IMP_MANTENIMIENTO_05");
        variable_IMP_INVERSION_01 = (JRFillVariable)vm.get("IMP_INVERSION_01");
        variable_IMP_INVERSION_02 = (JRFillVariable)vm.get("IMP_INVERSION_02");
        variable_IMP_INVERSION_03 = (JRFillVariable)vm.get("IMP_INVERSION_03");
        variable_IMP_INVERSION_04 = (JRFillVariable)vm.get("IMP_INVERSION_04");
        variable_IMP_INVERSION_05 = (JRFillVariable)vm.get("IMP_INVERSION_05");
        variable_IMP_MANTENIMIENTO_TOTAL = (JRFillVariable)vm.get("IMP_MANTENIMIENTO_TOTAL");
        variable_IMP_INVERSION_TOTAL = (JRFillVariable)vm.get("IMP_INVERSION_TOTAL");
        variable_IMP_TOTAL_TOTAL = (JRFillVariable)vm.get("IMP_TOTAL_TOTAL");
        variable_Resultado_Final_COUNT = (JRFillVariable)vm.get("Resultado_Final_COUNT");
        variable_Grupo_Compañia_COUNT = (JRFillVariable)vm.get("Grupo_Compañia_COUNT");
        variable_Grupo_Area_COUNT = (JRFillVariable)vm.get("Grupo_Area_COUNT");
        variable_Grupo_Programa_COUNT = (JRFillVariable)vm.get("Grupo_Programa_COUNT");
        variable_Grupo_Subprograma_COUNT = (JRFillVariable)vm.get("Grupo_Subprograma_COUNT");
        variable_Grupo_Espacio_COUNT = (JRFillVariable)vm.get("Grupo_Espacio_COUNT");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 475 : // 475
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_INVERSION.getValue()));
                break;
            }
            case 523 : // 523
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 479 : // 479
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_MANTENIMIENTO.getValue()));
                break;
            }
            case 461 : // 461
            {
                value = (java.lang.Integer)(new Integer("2005"));
                break;
            }
            case 526 : // 526
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_05.getValue()));
                break;
            }
            case 471 : // 471
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_MANTENIMIENTO.getValue()));
                break;
            }
            case 477 : // 477
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_INVERSION.getValue()));
                break;
            }
            case 505 : // 505
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 467 : // 467
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_TOTAL.getValue()));
                break;
            }
            case 476 : // 476
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_INVERSION.getValue()));
                break;
            }
            case 474 : // 474
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_INVERSION.getValue()));
                break;
            }
            case 537 : // 537
            {
                value = (java.lang.String)(((java.lang.String)field_CD_ELEMENTO_06.getValue()));
                break;
            }
            case 498 : // 498
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)parameter_P3.getValue()).intValue()<=((java.lang.Double)field_CD_TIPOELEMENTO_02.getValue()).intValue()));
                break;
            }
            case 532 : // 532
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 528 : // 528
            {
                value = (java.lang.String)(((java.lang.String)field_CD_ELEMENTO_05.getValue()));
                break;
            }
            case 517 : // 517
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_04.getValue()));
                break;
            }
            case 470 : // 470
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_MANTENIMIENTO.getValue()));
                break;
            }
            case 464 : // 464
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_TOTAL.getValue()));
                break;
            }
            case 503 : // 503
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_MANTENIMIENTO_02.getValue()));
                break;
            }
            case 515 : // 515
            {
                value = (java.lang.Object)(((java.lang.String)field_CD_ELEMENTO_04.getValue()));
                break;
            }
            case 454 : // 454
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 497 : // 497
            {
                value = (java.lang.Object)(((java.lang.String)field_CD_ELEMENTO_02.getValue()));
                break;
            }
            case 538 : // 538
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_INVERSION.getValue()));
                break;
            }
            case 510 : // 510
            {
                value = (java.lang.String)(((java.lang.String)field_CD_ELEMENTO_03.getValue()));
                break;
            }
            case 468 : // 468
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_TOTAL.getValue()));
                break;
            }
            case 504 : // 504
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 507 : // 507
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)parameter_P3.getValue()).intValue()<=((java.lang.Double)field_CD_TIPOELEMENTO_03.getValue()).intValue()));
                break;
            }
            case 462 : // 462
            {
                value = (java.lang.Integer)(new Integer("3"));
                break;
            }
            case 463 : // 463
            {
                value = (java.lang.String)("");
                break;
            }
            case 531 : // 531
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 494 : // 494
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_MANTENIMIENTO_01.getValue()));
                break;
            }
            case 453 : // 453
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 458 : // 458
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 540 : // 540
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getValue()));
                break;
            }
            case 535 : // 535
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_06.getValue()));
                break;
            }
            case 519 : // 519
            {
                value = (java.lang.String)(((java.lang.String)field_CD_ELEMENTO_04.getValue()));
                break;
            }
            case 455 : // 455
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 484 : // 484
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_INVERSION_TOTAL.getValue()));
                break;
            }
            case 492 : // 492
            {
                value = (java.lang.String)(((java.lang.String)field_CD_ELEMENTO_01.getValue()));
                break;
            }
            case 465 : // 465
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_TOTAL.getValue()));
                break;
            }
            case 506 : // 506
            {
                value = (java.lang.Object)(((java.lang.String)field_CD_ELEMENTO_03.getValue()));
                break;
            }
            case 456 : // 456
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 478 : // 478
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_INVERSION.getValue()));
                break;
            }
            case 527 : // 527
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_TOTAL_05.getValue()));
                break;
            }
            case 530 : // 530
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_MANTENIMIENTO_05.getValue()));
                break;
            }
            case 452 : // 452
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 483 : // 483
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_MANTENIMIENTO_TOTAL.getValue()));
                break;
            }
            case 469 : // 469
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_MANTENIMIENTO.getValue()));
                break;
            }
            case 521 : // 521
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_MANTENIMIENTO_04.getValue()));
                break;
            }
            case 534 : // 534
            {
                value = (java.lang.Integer)(((java.lang.Integer)parameter_P2.getValue()));
                break;
            }
            case 516 : // 516
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)parameter_P3.getValue()).intValue()<=((java.lang.Double)field_CD_TIPOELEMENTO_04.getValue()).intValue()));
                break;
            }
            case 488 : // 488
            {
                value = (java.lang.Object)(((java.lang.String)field_CD_ELEMENTO_01.getValue()));
                break;
            }
            case 489 : // 489
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)parameter_P3.getValue()).intValue()<=((java.lang.Double)field_CD_TIPOELEMENTO_01.getValue()).intValue()));
                break;
            }
            case 509 : // 509
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_TOTAL_03.getValue()));
                break;
            }
            case 520 : // 520
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_INVERSION_04.getValue()));
                break;
            }
            case 472 : // 472
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_MANTENIMIENTO.getValue()));
                break;
            }
            case 508 : // 508
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_03.getValue()));
                break;
            }
            case 496 : // 496
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 536 : // 536
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_TOTAL.getValue()));
                break;
            }
            case 490 : // 490
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_01.getValue()));
                break;
            }
            case 487 : // 487
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 512 : // 512
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_MANTENIMIENTO_03.getValue()));
                break;
            }
            case 493 : // 493
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_INVERSION_01.getValue()));
                break;
            }
            case 495 : // 495
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 518 : // 518
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_TOTAL_04.getValue()));
                break;
            }
            case 500 : // 500
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_TOTAL_02.getValue()));
                break;
            }
            case 524 : // 524
            {
                value = (java.lang.Object)(((java.lang.String)field_CD_ELEMENTO_05.getValue()));
                break;
            }
            case 473 : // 473
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_MANTENIMIENTO.getValue()));
                break;
            }
            case 457 : // 457
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 511 : // 511
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_INVERSION_03.getValue()));
                break;
            }
            case 514 : // 514
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 466 : // 466
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_TOTAL.getValue()));
                break;
            }
            case 486 : // 486
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 459 : // 459
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 480 : // 480
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_INVERSION.getValue()));
                break;
            }
            case 502 : // 502
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_INVERSION_02.getValue()));
                break;
            }
            case 539 : // 539
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_MANTENIMIENTO.getValue()));
                break;
            }
            case 522 : // 522
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 485 : // 485
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_TOTAL_TOTAL.getValue()));
                break;
            }
            case 529 : // 529
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_INVERSION_05.getValue()));
                break;
            }
            case 533 : // 533
            {
                value = (java.lang.String)(java.util.Calendar.getInstance().get(java.util.Calendar.DATE)
+ "/" +
((java.util.Calendar.getInstance().get(java.util.Calendar.MONTH))+1)
+ "/" +
java.util.Calendar.getInstance().get(java.util.Calendar.YEAR));
                break;
            }
            case 501 : // 501
            {
                value = (java.lang.String)(((java.lang.String)field_CD_ELEMENTO_02.getValue()));
                break;
            }
            case 491 : // 491
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_TOTAL_01.getValue()));
                break;
            }
            case 481 : // 481
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_TOTAL.getValue()));
                break;
            }
            case 482 : // 482
            {
                value = (java.lang.Object)(null);
                break;
            }
            case 460 : // 460
            {
                value = (java.lang.String)(new String("Admin"));
                break;
            }
            case 541 : // 541
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getValue()));
                break;
            }
            case 499 : // 499
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_02.getValue()));
                break;
            }
            case 513 : // 513
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 525 : // 525
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)parameter_P3.getValue()).intValue()<=((java.lang.Double)field_CD_TIPOELEMENTO_05.getValue()).intValue()));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 475 : // 475
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_INVERSION.getOldValue()));
                break;
            }
            case 523 : // 523
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 479 : // 479
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_MANTENIMIENTO.getOldValue()));
                break;
            }
            case 461 : // 461
            {
                value = (java.lang.Integer)(new Integer("2005"));
                break;
            }
            case 526 : // 526
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_05.getOldValue()));
                break;
            }
            case 471 : // 471
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_MANTENIMIENTO.getOldValue()));
                break;
            }
            case 477 : // 477
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_INVERSION.getOldValue()));
                break;
            }
            case 505 : // 505
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 467 : // 467
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_TOTAL.getOldValue()));
                break;
            }
            case 476 : // 476
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_INVERSION.getOldValue()));
                break;
            }
            case 474 : // 474
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_INVERSION.getOldValue()));
                break;
            }
            case 537 : // 537
            {
                value = (java.lang.String)(((java.lang.String)field_CD_ELEMENTO_06.getOldValue()));
                break;
            }
            case 498 : // 498
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)parameter_P3.getValue()).intValue()<=((java.lang.Double)field_CD_TIPOELEMENTO_02.getOldValue()).intValue()));
                break;
            }
            case 532 : // 532
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 528 : // 528
            {
                value = (java.lang.String)(((java.lang.String)field_CD_ELEMENTO_05.getOldValue()));
                break;
            }
            case 517 : // 517
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_04.getOldValue()));
                break;
            }
            case 470 : // 470
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_MANTENIMIENTO.getOldValue()));
                break;
            }
            case 464 : // 464
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_TOTAL.getOldValue()));
                break;
            }
            case 503 : // 503
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_MANTENIMIENTO_02.getOldValue()));
                break;
            }
            case 515 : // 515
            {
                value = (java.lang.Object)(((java.lang.String)field_CD_ELEMENTO_04.getOldValue()));
                break;
            }
            case 454 : // 454
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 497 : // 497
            {
                value = (java.lang.Object)(((java.lang.String)field_CD_ELEMENTO_02.getOldValue()));
                break;
            }
            case 538 : // 538
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_INVERSION.getOldValue()));
                break;
            }
            case 510 : // 510
            {
                value = (java.lang.String)(((java.lang.String)field_CD_ELEMENTO_03.getOldValue()));
                break;
            }
            case 468 : // 468
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_TOTAL.getOldValue()));
                break;
            }
            case 504 : // 504
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 507 : // 507
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)parameter_P3.getValue()).intValue()<=((java.lang.Double)field_CD_TIPOELEMENTO_03.getOldValue()).intValue()));
                break;
            }
            case 462 : // 462
            {
                value = (java.lang.Integer)(new Integer("3"));
                break;
            }
            case 463 : // 463
            {
                value = (java.lang.String)("");
                break;
            }
            case 531 : // 531
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 494 : // 494
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_MANTENIMIENTO_01.getOldValue()));
                break;
            }
            case 453 : // 453
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 458 : // 458
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 540 : // 540
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()));
                break;
            }
            case 535 : // 535
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_06.getOldValue()));
                break;
            }
            case 519 : // 519
            {
                value = (java.lang.String)(((java.lang.String)field_CD_ELEMENTO_04.getOldValue()));
                break;
            }
            case 455 : // 455
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 484 : // 484
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_INVERSION_TOTAL.getOldValue()));
                break;
            }
            case 492 : // 492
            {
                value = (java.lang.String)(((java.lang.String)field_CD_ELEMENTO_01.getOldValue()));
                break;
            }
            case 465 : // 465
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_TOTAL.getOldValue()));
                break;
            }
            case 506 : // 506
            {
                value = (java.lang.Object)(((java.lang.String)field_CD_ELEMENTO_03.getOldValue()));
                break;
            }
            case 456 : // 456
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 478 : // 478
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_INVERSION.getOldValue()));
                break;
            }
            case 527 : // 527
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_TOTAL_05.getOldValue()));
                break;
            }
            case 530 : // 530
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_MANTENIMIENTO_05.getOldValue()));
                break;
            }
            case 452 : // 452
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 483 : // 483
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_MANTENIMIENTO_TOTAL.getOldValue()));
                break;
            }
            case 469 : // 469
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_MANTENIMIENTO.getOldValue()));
                break;
            }
            case 521 : // 521
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_MANTENIMIENTO_04.getOldValue()));
                break;
            }
            case 534 : // 534
            {
                value = (java.lang.Integer)(((java.lang.Integer)parameter_P2.getValue()));
                break;
            }
            case 516 : // 516
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)parameter_P3.getValue()).intValue()<=((java.lang.Double)field_CD_TIPOELEMENTO_04.getOldValue()).intValue()));
                break;
            }
            case 488 : // 488
            {
                value = (java.lang.Object)(((java.lang.String)field_CD_ELEMENTO_01.getOldValue()));
                break;
            }
            case 489 : // 489
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)parameter_P3.getValue()).intValue()<=((java.lang.Double)field_CD_TIPOELEMENTO_01.getOldValue()).intValue()));
                break;
            }
            case 509 : // 509
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_TOTAL_03.getOldValue()));
                break;
            }
            case 520 : // 520
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_INVERSION_04.getOldValue()));
                break;
            }
            case 472 : // 472
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_MANTENIMIENTO.getOldValue()));
                break;
            }
            case 508 : // 508
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_03.getOldValue()));
                break;
            }
            case 496 : // 496
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 536 : // 536
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_TOTAL.getOldValue()));
                break;
            }
            case 490 : // 490
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_01.getOldValue()));
                break;
            }
            case 487 : // 487
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 512 : // 512
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_MANTENIMIENTO_03.getOldValue()));
                break;
            }
            case 493 : // 493
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_INVERSION_01.getOldValue()));
                break;
            }
            case 495 : // 495
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 518 : // 518
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_TOTAL_04.getOldValue()));
                break;
            }
            case 500 : // 500
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_TOTAL_02.getOldValue()));
                break;
            }
            case 524 : // 524
            {
                value = (java.lang.Object)(((java.lang.String)field_CD_ELEMENTO_05.getOldValue()));
                break;
            }
            case 473 : // 473
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_MANTENIMIENTO.getOldValue()));
                break;
            }
            case 457 : // 457
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 511 : // 511
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_INVERSION_03.getOldValue()));
                break;
            }
            case 514 : // 514
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 466 : // 466
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_TOTAL.getOldValue()));
                break;
            }
            case 486 : // 486
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 459 : // 459
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 480 : // 480
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_INVERSION.getOldValue()));
                break;
            }
            case 502 : // 502
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_INVERSION_02.getOldValue()));
                break;
            }
            case 539 : // 539
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_MANTENIMIENTO.getOldValue()));
                break;
            }
            case 522 : // 522
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 485 : // 485
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_TOTAL_TOTAL.getOldValue()));
                break;
            }
            case 529 : // 529
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_INVERSION_05.getOldValue()));
                break;
            }
            case 533 : // 533
            {
                value = (java.lang.String)(java.util.Calendar.getInstance().get(java.util.Calendar.DATE)
+ "/" +
((java.util.Calendar.getInstance().get(java.util.Calendar.MONTH))+1)
+ "/" +
java.util.Calendar.getInstance().get(java.util.Calendar.YEAR));
                break;
            }
            case 501 : // 501
            {
                value = (java.lang.String)(((java.lang.String)field_CD_ELEMENTO_02.getOldValue()));
                break;
            }
            case 491 : // 491
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_TOTAL_01.getOldValue()));
                break;
            }
            case 481 : // 481
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_TOTAL.getOldValue()));
                break;
            }
            case 482 : // 482
            {
                value = (java.lang.Object)(null);
                break;
            }
            case 460 : // 460
            {
                value = (java.lang.String)(new String("Admin"));
                break;
            }
            case 541 : // 541
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()));
                break;
            }
            case 499 : // 499
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_02.getOldValue()));
                break;
            }
            case 513 : // 513
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 525 : // 525
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)parameter_P3.getValue()).intValue()<=((java.lang.Double)field_CD_TIPOELEMENTO_05.getOldValue()).intValue()));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 475 : // 475
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_INVERSION.getValue()));
                break;
            }
            case 523 : // 523
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 479 : // 479
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_MANTENIMIENTO.getValue()));
                break;
            }
            case 461 : // 461
            {
                value = (java.lang.Integer)(new Integer("2005"));
                break;
            }
            case 526 : // 526
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_05.getValue()));
                break;
            }
            case 471 : // 471
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_MANTENIMIENTO.getValue()));
                break;
            }
            case 477 : // 477
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_INVERSION.getValue()));
                break;
            }
            case 505 : // 505
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 467 : // 467
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_TOTAL.getValue()));
                break;
            }
            case 476 : // 476
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_INVERSION.getValue()));
                break;
            }
            case 474 : // 474
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_INVERSION.getValue()));
                break;
            }
            case 537 : // 537
            {
                value = (java.lang.String)(((java.lang.String)field_CD_ELEMENTO_06.getValue()));
                break;
            }
            case 498 : // 498
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)parameter_P3.getValue()).intValue()<=((java.lang.Double)field_CD_TIPOELEMENTO_02.getValue()).intValue()));
                break;
            }
            case 532 : // 532
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 528 : // 528
            {
                value = (java.lang.String)(((java.lang.String)field_CD_ELEMENTO_05.getValue()));
                break;
            }
            case 517 : // 517
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_04.getValue()));
                break;
            }
            case 470 : // 470
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_MANTENIMIENTO.getValue()));
                break;
            }
            case 464 : // 464
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_TOTAL.getValue()));
                break;
            }
            case 503 : // 503
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_MANTENIMIENTO_02.getEstimatedValue()));
                break;
            }
            case 515 : // 515
            {
                value = (java.lang.Object)(((java.lang.String)field_CD_ELEMENTO_04.getValue()));
                break;
            }
            case 454 : // 454
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 497 : // 497
            {
                value = (java.lang.Object)(((java.lang.String)field_CD_ELEMENTO_02.getValue()));
                break;
            }
            case 538 : // 538
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_INVERSION.getValue()));
                break;
            }
            case 510 : // 510
            {
                value = (java.lang.String)(((java.lang.String)field_CD_ELEMENTO_03.getValue()));
                break;
            }
            case 468 : // 468
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_TOTAL.getValue()));
                break;
            }
            case 504 : // 504
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 507 : // 507
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)parameter_P3.getValue()).intValue()<=((java.lang.Double)field_CD_TIPOELEMENTO_03.getValue()).intValue()));
                break;
            }
            case 462 : // 462
            {
                value = (java.lang.Integer)(new Integer("3"));
                break;
            }
            case 463 : // 463
            {
                value = (java.lang.String)("");
                break;
            }
            case 531 : // 531
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 494 : // 494
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_MANTENIMIENTO_01.getEstimatedValue()));
                break;
            }
            case 453 : // 453
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 458 : // 458
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 540 : // 540
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()));
                break;
            }
            case 535 : // 535
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_06.getValue()));
                break;
            }
            case 519 : // 519
            {
                value = (java.lang.String)(((java.lang.String)field_CD_ELEMENTO_04.getValue()));
                break;
            }
            case 455 : // 455
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 484 : // 484
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_INVERSION_TOTAL.getEstimatedValue()));
                break;
            }
            case 492 : // 492
            {
                value = (java.lang.String)(((java.lang.String)field_CD_ELEMENTO_01.getValue()));
                break;
            }
            case 465 : // 465
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_TOTAL.getValue()));
                break;
            }
            case 506 : // 506
            {
                value = (java.lang.Object)(((java.lang.String)field_CD_ELEMENTO_03.getValue()));
                break;
            }
            case 456 : // 456
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 478 : // 478
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_INVERSION.getValue()));
                break;
            }
            case 527 : // 527
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_TOTAL_05.getEstimatedValue()));
                break;
            }
            case 530 : // 530
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_MANTENIMIENTO_05.getEstimatedValue()));
                break;
            }
            case 452 : // 452
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 483 : // 483
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_MANTENIMIENTO_TOTAL.getEstimatedValue()));
                break;
            }
            case 469 : // 469
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_MANTENIMIENTO.getValue()));
                break;
            }
            case 521 : // 521
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_MANTENIMIENTO_04.getEstimatedValue()));
                break;
            }
            case 534 : // 534
            {
                value = (java.lang.Integer)(((java.lang.Integer)parameter_P2.getValue()));
                break;
            }
            case 516 : // 516
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)parameter_P3.getValue()).intValue()<=((java.lang.Double)field_CD_TIPOELEMENTO_04.getValue()).intValue()));
                break;
            }
            case 488 : // 488
            {
                value = (java.lang.Object)(((java.lang.String)field_CD_ELEMENTO_01.getValue()));
                break;
            }
            case 489 : // 489
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)parameter_P3.getValue()).intValue()<=((java.lang.Double)field_CD_TIPOELEMENTO_01.getValue()).intValue()));
                break;
            }
            case 509 : // 509
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_TOTAL_03.getEstimatedValue()));
                break;
            }
            case 520 : // 520
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_INVERSION_04.getEstimatedValue()));
                break;
            }
            case 472 : // 472
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_MANTENIMIENTO.getValue()));
                break;
            }
            case 508 : // 508
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_03.getValue()));
                break;
            }
            case 496 : // 496
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 536 : // 536
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_TOTAL.getValue()));
                break;
            }
            case 490 : // 490
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_01.getValue()));
                break;
            }
            case 487 : // 487
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 512 : // 512
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_MANTENIMIENTO_03.getEstimatedValue()));
                break;
            }
            case 493 : // 493
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_INVERSION_01.getEstimatedValue()));
                break;
            }
            case 495 : // 495
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 518 : // 518
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_TOTAL_04.getEstimatedValue()));
                break;
            }
            case 500 : // 500
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_TOTAL_02.getEstimatedValue()));
                break;
            }
            case 524 : // 524
            {
                value = (java.lang.Object)(((java.lang.String)field_CD_ELEMENTO_05.getValue()));
                break;
            }
            case 473 : // 473
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_MANTENIMIENTO.getValue()));
                break;
            }
            case 457 : // 457
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 511 : // 511
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_INVERSION_03.getEstimatedValue()));
                break;
            }
            case 514 : // 514
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 466 : // 466
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_TOTAL.getValue()));
                break;
            }
            case 486 : // 486
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 459 : // 459
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 480 : // 480
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_INVERSION.getValue()));
                break;
            }
            case 502 : // 502
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_INVERSION_02.getEstimatedValue()));
                break;
            }
            case 539 : // 539
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_MANTENIMIENTO.getValue()));
                break;
            }
            case 522 : // 522
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 485 : // 485
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_TOTAL_TOTAL.getEstimatedValue()));
                break;
            }
            case 529 : // 529
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_INVERSION_05.getEstimatedValue()));
                break;
            }
            case 533 : // 533
            {
                value = (java.lang.String)(java.util.Calendar.getInstance().get(java.util.Calendar.DATE)
+ "/" +
((java.util.Calendar.getInstance().get(java.util.Calendar.MONTH))+1)
+ "/" +
java.util.Calendar.getInstance().get(java.util.Calendar.YEAR));
                break;
            }
            case 501 : // 501
            {
                value = (java.lang.String)(((java.lang.String)field_CD_ELEMENTO_02.getValue()));
                break;
            }
            case 491 : // 491
            {
                value = (java.lang.Double)(((java.lang.Double)variable_IMP_TOTAL_01.getEstimatedValue()));
                break;
            }
            case 481 : // 481
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_TOTAL.getValue()));
                break;
            }
            case 482 : // 482
            {
                value = (java.lang.Object)(null);
                break;
            }
            case 460 : // 460
            {
                value = (java.lang.String)(new String("Admin"));
                break;
            }
            case 541 : // 541
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()));
                break;
            }
            case 499 : // 499
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_02.getValue()));
                break;
            }
            case 513 : // 513
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 525 : // 525
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)parameter_P3.getValue()).intValue()<=((java.lang.Double)field_CD_TIPOELEMENTO_05.getValue()).intValue()));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
