/*
 * Generated by JasperReports - 16/07/08 12:57
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;

import java.util.*;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.data.*;


/**
 *
 */
public class RPT_44 extends JRCalculator
{


    /**
     *
     */
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillParameter parameter_P4 = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_P1 = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_P2 = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillParameter parameter_P3 = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;

    private JRFillField field_SUM_IMP_ASIGNADO = null;
    private JRFillField field_IMP_ASIGNADO = null;
    private JRFillField field_CONT_PROYECTOS = null;
    private JRFillField field_DS_AREA = null;
    private JRFillField field_SUM_CONT_PROYECTOS = null;
    private JRFillField field_DS_CCAA = null;
    private JRFillField field_DS_ELEMENTO = null;

    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_PORC_CIEN = null;
    private JRFillVariable variable_SUM_NUM = null;
    private JRFillVariable variable_SUM_AREA = null;
    private JRFillVariable variable_AREA_COUNT = null;
    private JRFillVariable variable_Grupo_Elemento_COUNT = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
        parameter_P4 = (JRFillParameter)pm.get("P4");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_P1 = (JRFillParameter)pm.get("P1");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_P2 = (JRFillParameter)pm.get("P2");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
        parameter_P3 = (JRFillParameter)pm.get("P3");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
        field_SUM_IMP_ASIGNADO = (JRFillField)fm.get("SUM_IMP_ASIGNADO");
        field_IMP_ASIGNADO = (JRFillField)fm.get("IMP_ASIGNADO");
        field_CONT_PROYECTOS = (JRFillField)fm.get("CONT_PROYECTOS");
        field_DS_AREA = (JRFillField)fm.get("DS_AREA");
        field_SUM_CONT_PROYECTOS = (JRFillField)fm.get("SUM_CONT_PROYECTOS");
        field_DS_CCAA = (JRFillField)fm.get("DS_CCAA");
        field_DS_ELEMENTO = (JRFillField)fm.get("DS_ELEMENTO");
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
        variable_PORC_CIEN = (JRFillVariable)vm.get("PORC_CIEN");
        variable_SUM_NUM = (JRFillVariable)vm.get("SUM_NUM");
        variable_SUM_AREA = (JRFillVariable)vm.get("SUM_AREA");
        variable_AREA_COUNT = (JRFillVariable)vm.get("AREA_COUNT");
        variable_Grupo_Elemento_COUNT = (JRFillVariable)vm.get("Grupo_Elemento_COUNT");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 3257 : // 3257
            {
                value = (java.lang.Double)(((java.lang.Double)field_SUM_IMP_ASIGNADO.getValue()));
                break;
            }
            case 3278 : // 3278
            {
                value = (java.lang.Double)(((java.lang.Double)field_CONT_PROYECTOS.getValue()));
                break;
            }
            case 3263 : // 3263
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 3282 : // 3282
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getValue()));
                break;
            }
            case 3276 : // 3276
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_ASIGNADO.getValue()));
                break;
            }
            case 3266 : // 3266
            {
                value = (java.lang.Double)(((java.lang.Double)variable_PORC_CIEN.getValue()));
                break;
            }
            case 3277 : // 3277
            {
                value = (java.lang.String)(((java.lang.String)field_DS_CCAA.getValue()));
                break;
            }
            case 3255 : // 3255
            {
                value = (java.lang.Double)(new Double("100"));
                break;
            }
            case 3245 : // 3245
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3275 : // 3275
            {
                value = (java.lang.String)("Área: "+ ((java.lang.String)field_DS_AREA.getValue()));
                break;
            }
            case 3248 : // 3248
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3259 : // 3259
            {
                value = (java.lang.Boolean)(Boolean.valueOf(((java.lang.String)field_DS_AREA.getValue())!=null));
                break;
            }
            case 3261 : // 3261
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_AREA.getValue()));
                break;
            }
            case 3256 : // 3256
            {
                value = (java.lang.Double)(((java.lang.Double)field_CONT_PROYECTOS.getValue()));
                break;
            }
            case 3244 : // 3244
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3269 : // 3269
            {
                value = (java.lang.Double)(((java.lang.Double)field_SUM_IMP_ASIGNADO.getValue()));
                break;
            }
            case 3258 : // 3258
            {
                value = (java.lang.Object)(((java.lang.String)field_DS_AREA.getValue()));
                break;
            }
            case 3271 : // 3271
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 3281 : // 3281
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getValue()));
                break;
            }
            case 3279 : // 3279
            {
                value = (java.lang.Double)(new Double((((java.lang.Double)field_CONT_PROYECTOS.getValue()).doubleValue() * 100) / ((java.lang.Double)field_SUM_CONT_PROYECTOS.getValue()).doubleValue()));
                break;
            }
            case 3272 : // 3272
            {
                value = (java.lang.String)(java.util.Calendar.getInstance().get(java.util.Calendar.DATE)
+ "/" +
((java.util.Calendar.getInstance().get(java.util.Calendar.MONTH))+1)
+ "/" +
java.util.Calendar.getInstance().get(java.util.Calendar.YEAR));
                break;
            }
            case 3249 : // 3249
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 3246 : // 3246
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3250 : // 3250
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3254 : // 3254
            {
                value = (java.lang.String)(new String("CU"));
                break;
            }
            case 3280 : // 3280
            {
                value = (java.lang.Double)(new Double((((java.lang.Double)field_IMP_ASIGNADO.getValue()).doubleValue() * 100) / ((java.lang.Double)field_SUM_IMP_ASIGNADO.getValue()).doubleValue()));
                break;
            }
            case 3274 : // 3274
            {
                value = (java.lang.Boolean)(Boolean.valueOf(((java.lang.String)field_DS_AREA.getValue())!=null));
                break;
            }
            case 3268 : // 3268
            {
                value = (java.lang.Double)(((java.lang.Double)field_SUM_CONT_PROYECTOS.getValue()));
                break;
            }
            case 3252 : // 3252
            {
                value = (java.lang.String)(new String("Admin"));
                break;
            }
            case 3251 : // 3251
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 3273 : // 3273
            {
                value = (java.lang.Integer)(((java.lang.Integer)parameter_P2.getValue()));
                break;
            }
            case 3247 : // 3247
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 3265 : // 3265
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO.getValue()));
                break;
            }
            case 3253 : // 3253
            {
                value = (java.lang.Integer)(new Integer("2008"));
                break;
            }
            case 3270 : // 3270
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3260 : // 3260
            {
                value = (java.lang.String)("Importe total del área "+((java.lang.String)field_DS_AREA.getValue()));
                break;
            }
            case 3264 : // 3264
            {
                value = (java.lang.Object)(((java.lang.String)field_DS_ELEMENTO.getValue()));
                break;
            }
            case 3267 : // 3267
            {
                value = (java.lang.Double)(((java.lang.Double)variable_PORC_CIEN.getValue()));
                break;
            }
            case 3262 : // 3262
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 3257 : // 3257
            {
                value = (java.lang.Double)(((java.lang.Double)field_SUM_IMP_ASIGNADO.getOldValue()));
                break;
            }
            case 3278 : // 3278
            {
                value = (java.lang.Double)(((java.lang.Double)field_CONT_PROYECTOS.getOldValue()));
                break;
            }
            case 3263 : // 3263
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 3282 : // 3282
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()));
                break;
            }
            case 3276 : // 3276
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_ASIGNADO.getOldValue()));
                break;
            }
            case 3266 : // 3266
            {
                value = (java.lang.Double)(((java.lang.Double)variable_PORC_CIEN.getOldValue()));
                break;
            }
            case 3277 : // 3277
            {
                value = (java.lang.String)(((java.lang.String)field_DS_CCAA.getOldValue()));
                break;
            }
            case 3255 : // 3255
            {
                value = (java.lang.Double)(new Double("100"));
                break;
            }
            case 3245 : // 3245
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3275 : // 3275
            {
                value = (java.lang.String)("Área: "+ ((java.lang.String)field_DS_AREA.getOldValue()));
                break;
            }
            case 3248 : // 3248
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3259 : // 3259
            {
                value = (java.lang.Boolean)(Boolean.valueOf(((java.lang.String)field_DS_AREA.getOldValue())!=null));
                break;
            }
            case 3261 : // 3261
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_AREA.getOldValue()));
                break;
            }
            case 3256 : // 3256
            {
                value = (java.lang.Double)(((java.lang.Double)field_CONT_PROYECTOS.getOldValue()));
                break;
            }
            case 3244 : // 3244
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3269 : // 3269
            {
                value = (java.lang.Double)(((java.lang.Double)field_SUM_IMP_ASIGNADO.getOldValue()));
                break;
            }
            case 3258 : // 3258
            {
                value = (java.lang.Object)(((java.lang.String)field_DS_AREA.getOldValue()));
                break;
            }
            case 3271 : // 3271
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 3281 : // 3281
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()));
                break;
            }
            case 3279 : // 3279
            {
                value = (java.lang.Double)(new Double((((java.lang.Double)field_CONT_PROYECTOS.getOldValue()).doubleValue() * 100) / ((java.lang.Double)field_SUM_CONT_PROYECTOS.getOldValue()).doubleValue()));
                break;
            }
            case 3272 : // 3272
            {
                value = (java.lang.String)(java.util.Calendar.getInstance().get(java.util.Calendar.DATE)
+ "/" +
((java.util.Calendar.getInstance().get(java.util.Calendar.MONTH))+1)
+ "/" +
java.util.Calendar.getInstance().get(java.util.Calendar.YEAR));
                break;
            }
            case 3249 : // 3249
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 3246 : // 3246
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3250 : // 3250
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3254 : // 3254
            {
                value = (java.lang.String)(new String("CU"));
                break;
            }
            case 3280 : // 3280
            {
                value = (java.lang.Double)(new Double((((java.lang.Double)field_IMP_ASIGNADO.getOldValue()).doubleValue() * 100) / ((java.lang.Double)field_SUM_IMP_ASIGNADO.getOldValue()).doubleValue()));
                break;
            }
            case 3274 : // 3274
            {
                value = (java.lang.Boolean)(Boolean.valueOf(((java.lang.String)field_DS_AREA.getOldValue())!=null));
                break;
            }
            case 3268 : // 3268
            {
                value = (java.lang.Double)(((java.lang.Double)field_SUM_CONT_PROYECTOS.getOldValue()));
                break;
            }
            case 3252 : // 3252
            {
                value = (java.lang.String)(new String("Admin"));
                break;
            }
            case 3251 : // 3251
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 3273 : // 3273
            {
                value = (java.lang.Integer)(((java.lang.Integer)parameter_P2.getValue()));
                break;
            }
            case 3247 : // 3247
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 3265 : // 3265
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO.getOldValue()));
                break;
            }
            case 3253 : // 3253
            {
                value = (java.lang.Integer)(new Integer("2008"));
                break;
            }
            case 3270 : // 3270
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3260 : // 3260
            {
                value = (java.lang.String)("Importe total del área "+((java.lang.String)field_DS_AREA.getOldValue()));
                break;
            }
            case 3264 : // 3264
            {
                value = (java.lang.Object)(((java.lang.String)field_DS_ELEMENTO.getOldValue()));
                break;
            }
            case 3267 : // 3267
            {
                value = (java.lang.Double)(((java.lang.Double)variable_PORC_CIEN.getOldValue()));
                break;
            }
            case 3262 : // 3262
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 3257 : // 3257
            {
                value = (java.lang.Double)(((java.lang.Double)field_SUM_IMP_ASIGNADO.getValue()));
                break;
            }
            case 3278 : // 3278
            {
                value = (java.lang.Double)(((java.lang.Double)field_CONT_PROYECTOS.getValue()));
                break;
            }
            case 3263 : // 3263
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 3282 : // 3282
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()));
                break;
            }
            case 3276 : // 3276
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_ASIGNADO.getValue()));
                break;
            }
            case 3266 : // 3266
            {
                value = (java.lang.Double)(((java.lang.Double)variable_PORC_CIEN.getEstimatedValue()));
                break;
            }
            case 3277 : // 3277
            {
                value = (java.lang.String)(((java.lang.String)field_DS_CCAA.getValue()));
                break;
            }
            case 3255 : // 3255
            {
                value = (java.lang.Double)(new Double("100"));
                break;
            }
            case 3245 : // 3245
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3275 : // 3275
            {
                value = (java.lang.String)("Área: "+ ((java.lang.String)field_DS_AREA.getValue()));
                break;
            }
            case 3248 : // 3248
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3259 : // 3259
            {
                value = (java.lang.Boolean)(Boolean.valueOf(((java.lang.String)field_DS_AREA.getValue())!=null));
                break;
            }
            case 3261 : // 3261
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_AREA.getEstimatedValue()));
                break;
            }
            case 3256 : // 3256
            {
                value = (java.lang.Double)(((java.lang.Double)field_CONT_PROYECTOS.getValue()));
                break;
            }
            case 3244 : // 3244
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3269 : // 3269
            {
                value = (java.lang.Double)(((java.lang.Double)field_SUM_IMP_ASIGNADO.getValue()));
                break;
            }
            case 3258 : // 3258
            {
                value = (java.lang.Object)(((java.lang.String)field_DS_AREA.getValue()));
                break;
            }
            case 3271 : // 3271
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 3281 : // 3281
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()));
                break;
            }
            case 3279 : // 3279
            {
                value = (java.lang.Double)(new Double((((java.lang.Double)field_CONT_PROYECTOS.getValue()).doubleValue() * 100) / ((java.lang.Double)field_SUM_CONT_PROYECTOS.getValue()).doubleValue()));
                break;
            }
            case 3272 : // 3272
            {
                value = (java.lang.String)(java.util.Calendar.getInstance().get(java.util.Calendar.DATE)
+ "/" +
((java.util.Calendar.getInstance().get(java.util.Calendar.MONTH))+1)
+ "/" +
java.util.Calendar.getInstance().get(java.util.Calendar.YEAR));
                break;
            }
            case 3249 : // 3249
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 3246 : // 3246
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3250 : // 3250
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3254 : // 3254
            {
                value = (java.lang.String)(new String("CU"));
                break;
            }
            case 3280 : // 3280
            {
                value = (java.lang.Double)(new Double((((java.lang.Double)field_IMP_ASIGNADO.getValue()).doubleValue() * 100) / ((java.lang.Double)field_SUM_IMP_ASIGNADO.getValue()).doubleValue()));
                break;
            }
            case 3274 : // 3274
            {
                value = (java.lang.Boolean)(Boolean.valueOf(((java.lang.String)field_DS_AREA.getValue())!=null));
                break;
            }
            case 3268 : // 3268
            {
                value = (java.lang.Double)(((java.lang.Double)field_SUM_CONT_PROYECTOS.getValue()));
                break;
            }
            case 3252 : // 3252
            {
                value = (java.lang.String)(new String("Admin"));
                break;
            }
            case 3251 : // 3251
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 3273 : // 3273
            {
                value = (java.lang.Integer)(((java.lang.Integer)parameter_P2.getValue()));
                break;
            }
            case 3247 : // 3247
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 3265 : // 3265
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO.getValue()));
                break;
            }
            case 3253 : // 3253
            {
                value = (java.lang.Integer)(new Integer("2008"));
                break;
            }
            case 3270 : // 3270
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3260 : // 3260
            {
                value = (java.lang.String)("Importe total del área "+((java.lang.String)field_DS_AREA.getValue()));
                break;
            }
            case 3264 : // 3264
            {
                value = (java.lang.Object)(((java.lang.String)field_DS_ELEMENTO.getValue()));
                break;
            }
            case 3267 : // 3267
            {
                value = (java.lang.Double)(((java.lang.Double)variable_PORC_CIEN.getEstimatedValue()));
                break;
            }
            case 3262 : // 3262
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
