/*
 * Generated by JasperReports - 25/11/05 14:12
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;

import java.util.*;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.data.*;


/**
 *
 */
public class rpt_EstRepOfic52 extends JRCalculator
{


    /**
     *
     */
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillParameter parameter_P1 = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;

    private JRFillField field_DESTINO = null;
    private JRFillField field_CD_PUBLICACION = null;
    private JRFillField field_CD_SALIDA = null;
    private JRFillField field_CLAVE = null;
    private JRFillField field_SALIDAS = null;
    private JRFillField field_PUBLICACION = null;
    private JRFillField field_CODIGO = null;
    private JRFillField field_TITULO = null;

    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_SALIDASCODIGO = null;
    private JRFillVariable variable_SALIDASOFICINA = null;
    private JRFillVariable variable_CLAVE_COUNT = null;
    private JRFillVariable variable_CD_OFICINA_COUNT = null;
    private JRFillVariable variable_CODIGO_COUNT = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
        parameter_P1 = (JRFillParameter)pm.get("P1");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
        field_DESTINO = (JRFillField)fm.get("DESTINO");
        field_CD_PUBLICACION = (JRFillField)fm.get("CD_PUBLICACION");
        field_CD_SALIDA = (JRFillField)fm.get("CD_SALIDA");
        field_CLAVE = (JRFillField)fm.get("CLAVE");
        field_SALIDAS = (JRFillField)fm.get("SALIDAS");
        field_PUBLICACION = (JRFillField)fm.get("PUBLICACION");
        field_CODIGO = (JRFillField)fm.get("CODIGO");
        field_TITULO = (JRFillField)fm.get("TITULO");
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
        variable_SALIDASCODIGO = (JRFillVariable)vm.get("SALIDASCODIGO");
        variable_SALIDASOFICINA = (JRFillVariable)vm.get("SALIDASOFICINA");
        variable_CLAVE_COUNT = (JRFillVariable)vm.get("CLAVE_COUNT");
        variable_CD_OFICINA_COUNT = (JRFillVariable)vm.get("CD_OFICINA_COUNT");
        variable_CODIGO_COUNT = (JRFillVariable)vm.get("CODIGO_COUNT");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 1231 : // 1231
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1218 : // 1218
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_SALIDAS.getValue()));
                break;
            }
            case 1210 : // 1210
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1216 : // 1216
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1225 : // 1225
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1212 : // 1212
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1234 : // 1234
            {
                value = (java.lang.String)(((java.lang.String)field_PUBLICACION.getValue()));
                break;
            }
            case 1215 : // 1215
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1236 : // 1236
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1219 : // 1219
            {
                value = (java.lang.Integer)(new Integer("0"));
                break;
            }
            case 1217 : // 1217
            {
                value = (java.lang.String)("");
                break;
            }
            case 1235 : // 1235
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_SALIDASCODIGO.getValue()));
                break;
            }
            case 1209 : // 1209
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1223 : // 1223
            {
                value = (java.lang.String)(((java.lang.String)field_CLAVE.getValue()));
                break;
            }
            case 1239 : // 1239
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getValue()));
                break;
            }
            case 1233 : // 1233
            {
                value = (java.lang.String)(((java.lang.String)field_CODIGO.getValue()));
                break;
            }
            case 1229 : // 1229
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_SALIDASOFICINA.getValue()));
                break;
            }
            case 1221 : // 1221
            {
                value = (java.lang.Integer)(new Integer("0"));
                break;
            }
            case 1230 : // 1230
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1222 : // 1222
            {
                value = (java.lang.Object)(((java.lang.String)field_CLAVE.getValue()));
                break;
            }
            case 1227 : // 1227
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_DESTINO.getValue()));
                break;
            }
            case 1226 : // 1226
            {
                value = (java.lang.Object)(((java.lang.Integer)field_DESTINO.getValue()));
                break;
            }
            case 1237 : // 1237
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1228 : // 1228
            {
                value = (java.lang.String)(((java.lang.String)field_TITULO.getValue()));
                break;
            }
            case 1214 : // 1214
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1220 : // 1220
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_SALIDAS.getValue()));
                break;
            }
            case 1238 : // 1238
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getValue()));
                break;
            }
            case 1224 : // 1224
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1213 : // 1213
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1232 : // 1232
            {
                value = (java.lang.Object)(((java.lang.String)field_CODIGO.getValue()));
                break;
            }
            case 1211 : // 1211
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 1231 : // 1231
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1218 : // 1218
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_SALIDAS.getOldValue()));
                break;
            }
            case 1210 : // 1210
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1216 : // 1216
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1225 : // 1225
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1212 : // 1212
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1234 : // 1234
            {
                value = (java.lang.String)(((java.lang.String)field_PUBLICACION.getOldValue()));
                break;
            }
            case 1215 : // 1215
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1236 : // 1236
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1219 : // 1219
            {
                value = (java.lang.Integer)(new Integer("0"));
                break;
            }
            case 1217 : // 1217
            {
                value = (java.lang.String)("");
                break;
            }
            case 1235 : // 1235
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_SALIDASCODIGO.getOldValue()));
                break;
            }
            case 1209 : // 1209
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1223 : // 1223
            {
                value = (java.lang.String)(((java.lang.String)field_CLAVE.getOldValue()));
                break;
            }
            case 1239 : // 1239
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()));
                break;
            }
            case 1233 : // 1233
            {
                value = (java.lang.String)(((java.lang.String)field_CODIGO.getOldValue()));
                break;
            }
            case 1229 : // 1229
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_SALIDASOFICINA.getOldValue()));
                break;
            }
            case 1221 : // 1221
            {
                value = (java.lang.Integer)(new Integer("0"));
                break;
            }
            case 1230 : // 1230
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1222 : // 1222
            {
                value = (java.lang.Object)(((java.lang.String)field_CLAVE.getOldValue()));
                break;
            }
            case 1227 : // 1227
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_DESTINO.getOldValue()));
                break;
            }
            case 1226 : // 1226
            {
                value = (java.lang.Object)(((java.lang.Integer)field_DESTINO.getOldValue()));
                break;
            }
            case 1237 : // 1237
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1228 : // 1228
            {
                value = (java.lang.String)(((java.lang.String)field_TITULO.getOldValue()));
                break;
            }
            case 1214 : // 1214
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1220 : // 1220
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_SALIDAS.getOldValue()));
                break;
            }
            case 1238 : // 1238
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()));
                break;
            }
            case 1224 : // 1224
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1213 : // 1213
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1232 : // 1232
            {
                value = (java.lang.Object)(((java.lang.String)field_CODIGO.getOldValue()));
                break;
            }
            case 1211 : // 1211
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 1231 : // 1231
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1218 : // 1218
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_SALIDAS.getValue()));
                break;
            }
            case 1210 : // 1210
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1216 : // 1216
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1225 : // 1225
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1212 : // 1212
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1234 : // 1234
            {
                value = (java.lang.String)(((java.lang.String)field_PUBLICACION.getValue()));
                break;
            }
            case 1215 : // 1215
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1236 : // 1236
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1219 : // 1219
            {
                value = (java.lang.Integer)(new Integer("0"));
                break;
            }
            case 1217 : // 1217
            {
                value = (java.lang.String)("");
                break;
            }
            case 1235 : // 1235
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_SALIDASCODIGO.getEstimatedValue()));
                break;
            }
            case 1209 : // 1209
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1223 : // 1223
            {
                value = (java.lang.String)(((java.lang.String)field_CLAVE.getValue()));
                break;
            }
            case 1239 : // 1239
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()));
                break;
            }
            case 1233 : // 1233
            {
                value = (java.lang.String)(((java.lang.String)field_CODIGO.getValue()));
                break;
            }
            case 1229 : // 1229
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_SALIDASOFICINA.getEstimatedValue()));
                break;
            }
            case 1221 : // 1221
            {
                value = (java.lang.Integer)(new Integer("0"));
                break;
            }
            case 1230 : // 1230
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1222 : // 1222
            {
                value = (java.lang.Object)(((java.lang.String)field_CLAVE.getValue()));
                break;
            }
            case 1227 : // 1227
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_DESTINO.getValue()));
                break;
            }
            case 1226 : // 1226
            {
                value = (java.lang.Object)(((java.lang.Integer)field_DESTINO.getValue()));
                break;
            }
            case 1237 : // 1237
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1228 : // 1228
            {
                value = (java.lang.String)(((java.lang.String)field_TITULO.getValue()));
                break;
            }
            case 1214 : // 1214
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1220 : // 1220
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_SALIDAS.getValue()));
                break;
            }
            case 1238 : // 1238
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()));
                break;
            }
            case 1224 : // 1224
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1213 : // 1213
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1232 : // 1232
            {
                value = (java.lang.Object)(((java.lang.String)field_CODIGO.getValue()));
                break;
            }
            case 1211 : // 1211
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
