/*
 * Generated by JasperReports - 25/11/05 13:38
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;

import java.util.*;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.data.*;


/**
 *
 */
public class RPT_168 extends JRCalculator
{


    /**
     *
     */
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillParameter parameter_P4 = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_P1 = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_P2 = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillParameter parameter_P3 = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;

    private JRFillField field_IMP_DESVIACION = null;
    private JRFillField field_CD_ELEMENTO_02 = null;
    private JRFillField field_DS_ELEMENTO_04 = null;
    private JRFillField field_CD_ELEMENTO_05 = null;
    private JRFillField field_CD_TIPOELEMENTO_02 = null;
    private JRFillField field_CD_TIPOELEMENTO_05 = null;
    private JRFillField field_IMP_COMPROMISO = null;
    private JRFillField field_DS_ELEMENTO_01 = null;
    private JRFillField field_CD_ELEMENTO_03 = null;
    private JRFillField field_DS_ELEMENTO_06 = null;
    private JRFillField field_CD_TIPOELEMENTO_01 = null;
    private JRFillField field_CD_ELEMENTO_04 = null;
    private JRFillField field_CD_TIPOELEMENTO_04 = null;
    private JRFillField field_DS_ELEMENTO_02 = null;
    private JRFillField field_IMP_ASIGNADO = null;
    private JRFillField field_IMP_PRESUPUESTO = null;
    private JRFillField field_DS_ELEMENTO_05 = null;
    private JRFillField field_CD_TIPOELEMENTO_03 = null;
    private JRFillField field_IMP_PAGO = null;
    private JRFillField field_IMP_GASTADO = null;
    private JRFillField field_CD_ELEMENTO_01 = null;
    private JRFillField field_CD_ELEMENTO_06 = null;
    private JRFillField field_DS_ELEMENTO_03 = null;
    private JRFillField field_CD_TIPOELEMENTO_06 = null;

    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_SUM_IMP_PRESUPUESTO_01 = null;
    private JRFillVariable variable_SUM_IMP_PRESUPUESTO_02 = null;
    private JRFillVariable variable_SUM_IMP_PRESUPUESTO_03 = null;
    private JRFillVariable variable_SUM_IMP_PRESUPUESTO_04 = null;
    private JRFillVariable variable_SUM_IMP_PRESUPUESTO_05 = null;
    private JRFillVariable variable_SUM_IMP_PRESUPUESTO_06 = null;
    private JRFillVariable variable_SUM_IMP_ASIGANDO_01 = null;
    private JRFillVariable variable_SUM_IMP_ASIGANDO_02 = null;
    private JRFillVariable variable_SUM_IMP_ASIGANDO_03 = null;
    private JRFillVariable variable_SUM_IMP_ASIGANDO_04 = null;
    private JRFillVariable variable_SUM_IMP_ASIGANDO_05 = null;
    private JRFillVariable variable_SUM_IMP_ASIGANDO_06 = null;
    private JRFillVariable variable_SUM_IMP_COMPROMISO_01 = null;
    private JRFillVariable variable_SUM_IMP_COMPROMISO_02 = null;
    private JRFillVariable variable_SUM_IMP_COMPROMISO_03 = null;
    private JRFillVariable variable_SUM_IMP_COMPROMISO_04 = null;
    private JRFillVariable variable_SUM_IMP_COMPROMISO_05 = null;
    private JRFillVariable variable_SUM_IMP_COMPROMISO_06 = null;
    private JRFillVariable variable_SUM_IMP_GASTADO_01 = null;
    private JRFillVariable variable_SUM_IMP_GASTADO_02 = null;
    private JRFillVariable variable_SUM_IMP_GASTADO_03 = null;
    private JRFillVariable variable_SUM_IMP_GASTADO_04 = null;
    private JRFillVariable variable_SUM_IMP_GASTADO_05 = null;
    private JRFillVariable variable_SUM_IMP_GASTADO_06 = null;
    private JRFillVariable variable_SUM_IMP_PAGO_01 = null;
    private JRFillVariable variable_SUM_IMP_PAGO_02 = null;
    private JRFillVariable variable_SUM_IMP_PAGO_03 = null;
    private JRFillVariable variable_SUM_IMP_PAGO_04 = null;
    private JRFillVariable variable_SUM_IMP_PAGO_05 = null;
    private JRFillVariable variable_SUM_IMP_PAGO_06 = null;
    private JRFillVariable variable_SUM_IMP_DESVIACION_01 = null;
    private JRFillVariable variable_SUM_IMP_DESVIACION_02 = null;
    private JRFillVariable variable_SUM_IMP_DESVIACION_03 = null;
    private JRFillVariable variable_SUM_IMP_DESVIACION_04 = null;
    private JRFillVariable variable_SUM_IMP_DESVIACION_05 = null;
    private JRFillVariable variable_SUM_IMP_DESVIACION_06 = null;
    private JRFillVariable variable_Grupo_Compañia_COUNT = null;
    private JRFillVariable variable_Grupo_Area_COUNT = null;
    private JRFillVariable variable_Grupo_Programa_COUNT = null;
    private JRFillVariable variable_Grupo_Subprograma_COUNT = null;
    private JRFillVariable variable_Grupo_Espacio_COUNT = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
        parameter_P4 = (JRFillParameter)pm.get("P4");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_P1 = (JRFillParameter)pm.get("P1");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_P2 = (JRFillParameter)pm.get("P2");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
        parameter_P3 = (JRFillParameter)pm.get("P3");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
        field_IMP_DESVIACION = (JRFillField)fm.get("IMP_DESVIACION");
        field_CD_ELEMENTO_02 = (JRFillField)fm.get("CD_ELEMENTO_02");
        field_DS_ELEMENTO_04 = (JRFillField)fm.get("DS_ELEMENTO_04");
        field_CD_ELEMENTO_05 = (JRFillField)fm.get("CD_ELEMENTO_05");
        field_CD_TIPOELEMENTO_02 = (JRFillField)fm.get("CD_TIPOELEMENTO_02");
        field_CD_TIPOELEMENTO_05 = (JRFillField)fm.get("CD_TIPOELEMENTO_05");
        field_IMP_COMPROMISO = (JRFillField)fm.get("IMP_COMPROMISO");
        field_DS_ELEMENTO_01 = (JRFillField)fm.get("DS_ELEMENTO_01");
        field_CD_ELEMENTO_03 = (JRFillField)fm.get("CD_ELEMENTO_03");
        field_DS_ELEMENTO_06 = (JRFillField)fm.get("DS_ELEMENTO_06");
        field_CD_TIPOELEMENTO_01 = (JRFillField)fm.get("CD_TIPOELEMENTO_01");
        field_CD_ELEMENTO_04 = (JRFillField)fm.get("CD_ELEMENTO_04");
        field_CD_TIPOELEMENTO_04 = (JRFillField)fm.get("CD_TIPOELEMENTO_04");
        field_DS_ELEMENTO_02 = (JRFillField)fm.get("DS_ELEMENTO_02");
        field_IMP_ASIGNADO = (JRFillField)fm.get("IMP_ASIGNADO");
        field_IMP_PRESUPUESTO = (JRFillField)fm.get("IMP_PRESUPUESTO");
        field_DS_ELEMENTO_05 = (JRFillField)fm.get("DS_ELEMENTO_05");
        field_CD_TIPOELEMENTO_03 = (JRFillField)fm.get("CD_TIPOELEMENTO_03");
        field_IMP_PAGO = (JRFillField)fm.get("IMP_PAGO");
        field_IMP_GASTADO = (JRFillField)fm.get("IMP_GASTADO");
        field_CD_ELEMENTO_01 = (JRFillField)fm.get("CD_ELEMENTO_01");
        field_CD_ELEMENTO_06 = (JRFillField)fm.get("CD_ELEMENTO_06");
        field_DS_ELEMENTO_03 = (JRFillField)fm.get("DS_ELEMENTO_03");
        field_CD_TIPOELEMENTO_06 = (JRFillField)fm.get("CD_TIPOELEMENTO_06");
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
        variable_SUM_IMP_PRESUPUESTO_01 = (JRFillVariable)vm.get("SUM_IMP_PRESUPUESTO_01");
        variable_SUM_IMP_PRESUPUESTO_02 = (JRFillVariable)vm.get("SUM_IMP_PRESUPUESTO_02");
        variable_SUM_IMP_PRESUPUESTO_03 = (JRFillVariable)vm.get("SUM_IMP_PRESUPUESTO_03");
        variable_SUM_IMP_PRESUPUESTO_04 = (JRFillVariable)vm.get("SUM_IMP_PRESUPUESTO_04");
        variable_SUM_IMP_PRESUPUESTO_05 = (JRFillVariable)vm.get("SUM_IMP_PRESUPUESTO_05");
        variable_SUM_IMP_PRESUPUESTO_06 = (JRFillVariable)vm.get("SUM_IMP_PRESUPUESTO_06");
        variable_SUM_IMP_ASIGANDO_01 = (JRFillVariable)vm.get("SUM_IMP_ASIGANDO_01");
        variable_SUM_IMP_ASIGANDO_02 = (JRFillVariable)vm.get("SUM_IMP_ASIGANDO_02");
        variable_SUM_IMP_ASIGANDO_03 = (JRFillVariable)vm.get("SUM_IMP_ASIGANDO_03");
        variable_SUM_IMP_ASIGANDO_04 = (JRFillVariable)vm.get("SUM_IMP_ASIGANDO_04");
        variable_SUM_IMP_ASIGANDO_05 = (JRFillVariable)vm.get("SUM_IMP_ASIGANDO_05");
        variable_SUM_IMP_ASIGANDO_06 = (JRFillVariable)vm.get("SUM_IMP_ASIGANDO_06");
        variable_SUM_IMP_COMPROMISO_01 = (JRFillVariable)vm.get("SUM_IMP_COMPROMISO_01");
        variable_SUM_IMP_COMPROMISO_02 = (JRFillVariable)vm.get("SUM_IMP_COMPROMISO_02");
        variable_SUM_IMP_COMPROMISO_03 = (JRFillVariable)vm.get("SUM_IMP_COMPROMISO_03");
        variable_SUM_IMP_COMPROMISO_04 = (JRFillVariable)vm.get("SUM_IMP_COMPROMISO_04");
        variable_SUM_IMP_COMPROMISO_05 = (JRFillVariable)vm.get("SUM_IMP_COMPROMISO_05");
        variable_SUM_IMP_COMPROMISO_06 = (JRFillVariable)vm.get("SUM_IMP_COMPROMISO_06");
        variable_SUM_IMP_GASTADO_01 = (JRFillVariable)vm.get("SUM_IMP_GASTADO_01");
        variable_SUM_IMP_GASTADO_02 = (JRFillVariable)vm.get("SUM_IMP_GASTADO_02");
        variable_SUM_IMP_GASTADO_03 = (JRFillVariable)vm.get("SUM_IMP_GASTADO_03");
        variable_SUM_IMP_GASTADO_04 = (JRFillVariable)vm.get("SUM_IMP_GASTADO_04");
        variable_SUM_IMP_GASTADO_05 = (JRFillVariable)vm.get("SUM_IMP_GASTADO_05");
        variable_SUM_IMP_GASTADO_06 = (JRFillVariable)vm.get("SUM_IMP_GASTADO_06");
        variable_SUM_IMP_PAGO_01 = (JRFillVariable)vm.get("SUM_IMP_PAGO_01");
        variable_SUM_IMP_PAGO_02 = (JRFillVariable)vm.get("SUM_IMP_PAGO_02");
        variable_SUM_IMP_PAGO_03 = (JRFillVariable)vm.get("SUM_IMP_PAGO_03");
        variable_SUM_IMP_PAGO_04 = (JRFillVariable)vm.get("SUM_IMP_PAGO_04");
        variable_SUM_IMP_PAGO_05 = (JRFillVariable)vm.get("SUM_IMP_PAGO_05");
        variable_SUM_IMP_PAGO_06 = (JRFillVariable)vm.get("SUM_IMP_PAGO_06");
        variable_SUM_IMP_DESVIACION_01 = (JRFillVariable)vm.get("SUM_IMP_DESVIACION_01");
        variable_SUM_IMP_DESVIACION_02 = (JRFillVariable)vm.get("SUM_IMP_DESVIACION_02");
        variable_SUM_IMP_DESVIACION_03 = (JRFillVariable)vm.get("SUM_IMP_DESVIACION_03");
        variable_SUM_IMP_DESVIACION_04 = (JRFillVariable)vm.get("SUM_IMP_DESVIACION_04");
        variable_SUM_IMP_DESVIACION_05 = (JRFillVariable)vm.get("SUM_IMP_DESVIACION_05");
        variable_SUM_IMP_DESVIACION_06 = (JRFillVariable)vm.get("SUM_IMP_DESVIACION_06");
        variable_Grupo_Compañia_COUNT = (JRFillVariable)vm.get("Grupo_Compañia_COUNT");
        variable_Grupo_Area_COUNT = (JRFillVariable)vm.get("Grupo_Area_COUNT");
        variable_Grupo_Programa_COUNT = (JRFillVariable)vm.get("Grupo_Programa_COUNT");
        variable_Grupo_Subprograma_COUNT = (JRFillVariable)vm.get("Grupo_Subprograma_COUNT");
        variable_Grupo_Espacio_COUNT = (JRFillVariable)vm.get("Grupo_Espacio_COUNT");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 399 : // 399
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_COMPROMISO_04.getValue()));
                break;
            }
            case 392 : // 392
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 327 : // 327
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PRESUPUESTO.getValue()));
                break;
            }
            case 325 : // 325
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PRESUPUESTO.getValue()));
                break;
            }
            case 342 : // 342
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_COMPROMISO.getValue()));
                break;
            }
            case 423 : // 423
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_DESVIACION.getValue()));
                break;
            }
            case 408 : // 408
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PRESUPUESTO_05.getValue()));
                break;
            }
            case 367 : // 367
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_GASTADO_01.getValue()));
                break;
            }
            case 335 : // 335
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_ASIGNADO.getValue()));
                break;
            }
            case 361 : // 361
            {
                value = (java.lang.Object)(((java.lang.Double)field_CD_ELEMENTO_01.getValue()));
                break;
            }
            case 401 : // 401
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PAGO_04.getValue()));
                break;
            }
            case 317 : // 317
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 341 : // 341
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_COMPROMISO.getValue()));
                break;
            }
            case 369 : // 369
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_DESVIACION_01.getValue()));
                break;
            }
            case 347 : // 347
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_GASTADO.getValue()));
                break;
            }
            case 391 : // 391
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_DESVIACION_03.getValue()));
                break;
            }
            case 331 : // 331
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_ASIGNADO.getValue()));
                break;
            }
            case 380 : // 380
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_DESVIACION_02.getValue()));
                break;
            }
            case 360 : // 360
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_DESVIACION.getValue()));
                break;
            }
            case 353 : // 353
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PAGO.getValue()));
                break;
            }
            case 373 : // 373
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)parameter_P3.getValue()).intValue()<=((java.lang.Double)field_CD_TIPOELEMENTO_02.getValue()).intValue()));
                break;
            }
            case 349 : // 349
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PAGO.getValue()));
                break;
            }
            case 382 : // 382
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 419 : // 419
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_ASIGNADO.getValue()));
                break;
            }
            case 313 : // 313
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 402 : // 402
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_DESVIACION_04.getValue()));
                break;
            }
            case 406 : // 406
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)parameter_P3.getValue()).intValue()<=((java.lang.Double)field_CD_TIPOELEMENTO_05.getValue()).intValue()));
                break;
            }
            case 321 : // 321
            {
                value = (java.lang.String)(new String("Admin"));
                break;
            }
            case 388 : // 388
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_COMPROMISO_03.getValue()));
                break;
            }
            case 328 : // 328
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PRESUPUESTO.getValue()));
                break;
            }
            case 354 : // 354
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PAGO.getValue()));
                break;
            }
            case 422 : // 422
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PAGO.getValue()));
                break;
            }
            case 330 : // 330
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PRESUPUESTO.getValue()));
                break;
            }
            case 378 : // 378
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_GASTADO_02.getValue()));
                break;
            }
            case 348 : // 348
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_GASTADO.getValue()));
                break;
            }
            case 412 : // 412
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PAGO_05.getValue()));
                break;
            }
            case 420 : // 420
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_COMPROMISO.getValue()));
                break;
            }
            case 352 : // 352
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PAGO.getValue()));
                break;
            }
            case 417 : // 417
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_06.getValue()));
                break;
            }
            case 318 : // 318
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 375 : // 375
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PRESUPUESTO_02.getValue()));
                break;
            }
            case 371 : // 371
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 322 : // 322
            {
                value = (java.lang.Integer)(new Integer("2005"));
                break;
            }
            case 346 : // 346
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_GASTADO.getValue()));
                break;
            }
            case 424 : // 424
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getValue()));
                break;
            }
            case 329 : // 329
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PRESUPUESTO.getValue()));
                break;
            }
            case 362 : // 362
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)parameter_P3.getValue()).intValue()<=((java.lang.Double)field_CD_TIPOELEMENTO_01.getValue()).intValue()));
                break;
            }
            case 343 : // 343
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_GASTADO.getValue()));
                break;
            }
            case 398 : // 398
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_ASIGANDO_04.getValue()));
                break;
            }
            case 404 : // 404
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 345 : // 345
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_GASTADO.getValue()));
                break;
            }
            case 357 : // 357
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_DESVIACION.getValue()));
                break;
            }
            case 397 : // 397
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PRESUPUESTO_04.getValue()));
                break;
            }
            case 358 : // 358
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_DESVIACION.getValue()));
                break;
            }
            case 351 : // 351
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PAGO.getValue()));
                break;
            }
            case 411 : // 411
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_GASTADO_05.getValue()));
                break;
            }
            case 326 : // 326
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PRESUPUESTO.getValue()));
                break;
            }
            case 365 : // 365
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_ASIGANDO_01.getValue()));
                break;
            }
            case 413 : // 413
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_DESVIACION_05.getValue()));
                break;
            }
            case 374 : // 374
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_02.getValue()));
                break;
            }
            case 356 : // 356
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_DESVIACION.getValue()));
                break;
            }
            case 350 : // 350
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PAGO.getValue()));
                break;
            }
            case 418 : // 418
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PRESUPUESTO.getValue()));
                break;
            }
            case 389 : // 389
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_GASTADO_03.getValue()));
                break;
            }
            case 338 : // 338
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_COMPROMISO.getValue()));
                break;
            }
            case 320 : // 320
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 332 : // 332
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_ASIGNADO.getValue()));
                break;
            }
            case 336 : // 336
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_ASIGNADO.getValue()));
                break;
            }
            case 393 : // 393
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 368 : // 368
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PAGO_01.getValue()));
                break;
            }
            case 355 : // 355
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_DESVIACION.getValue()));
                break;
            }
            case 381 : // 381
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 409 : // 409
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_ASIGANDO_05.getValue()));
                break;
            }
            case 339 : // 339
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_COMPROMISO.getValue()));
                break;
            }
            case 376 : // 376
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_ASIGANDO_02.getValue()));
                break;
            }
            case 407 : // 407
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_05.getValue()));
                break;
            }
            case 315 : // 315
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 383 : // 383
            {
                value = (java.lang.Object)(((java.lang.Double)field_CD_ELEMENTO_03.getValue()));
                break;
            }
            case 337 : // 337
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_COMPROMISO.getValue()));
                break;
            }
            case 416 : // 416
            {
                value = (java.lang.String)(java.util.Calendar.getInstance().get(java.util.Calendar.DATE)
+ "/" +
((java.util.Calendar.getInstance().get(java.util.Calendar.MONTH))+1)
+ "/" +
java.util.Calendar.getInstance().get(java.util.Calendar.YEAR));
                break;
            }
            case 384 : // 384
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)parameter_P3.getValue()).intValue()<=((java.lang.Double)field_CD_TIPOELEMENTO_03.getValue()).intValue()));
                break;
            }
            case 386 : // 386
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PRESUPUESTO_03.getValue()));
                break;
            }
            case 414 : // 414
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 405 : // 405
            {
                value = (java.lang.Object)(((java.lang.Double)field_CD_ELEMENTO_05.getValue()));
                break;
            }
            case 340 : // 340
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_COMPROMISO.getValue()));
                break;
            }
            case 314 : // 314
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 359 : // 359
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_DESVIACION.getValue()));
                break;
            }
            case 323 : // 323
            {
                value = (java.lang.Integer)(new Integer("2"));
                break;
            }
            case 377 : // 377
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_COMPROMISO_02.getValue()));
                break;
            }
            case 316 : // 316
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 324 : // 324
            {
                value = (java.lang.String)(new String("A1"));
                break;
            }
            case 421 : // 421
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_GASTADO.getValue()));
                break;
            }
            case 379 : // 379
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PAGO_02.getValue()));
                break;
            }
            case 425 : // 425
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getValue()));
                break;
            }
            case 334 : // 334
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_ASIGNADO.getValue()));
                break;
            }
            case 415 : // 415
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 385 : // 385
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_03.getValue()));
                break;
            }
            case 333 : // 333
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_ASIGNADO.getValue()));
                break;
            }
            case 344 : // 344
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_GASTADO.getValue()));
                break;
            }
            case 363 : // 363
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_01.getValue()));
                break;
            }
           default :
           {
               value = evaluate1(id);
           }
        }
        
        return value;
    }


    /**
     *
     */
    private Object evaluate1(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 319 : // 319
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 396 : // 396
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_04.getValue()));
                break;
            }
            case 372 : // 372
            {
                value = (java.lang.Object)(((java.lang.Double)field_CD_ELEMENTO_02.getValue()));
                break;
            }
            case 364 : // 364
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PRESUPUESTO_01.getValue()));
                break;
            }
            case 390 : // 390
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PAGO_03.getValue()));
                break;
            }
            case 366 : // 366
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_COMPROMISO_01.getValue()));
                break;
            }
            case 395 : // 395
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)parameter_P3.getValue()).intValue()<=((java.lang.Double)field_CD_TIPOELEMENTO_04.getValue()).intValue()));
                break;
            }
            case 400 : // 400
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_GASTADO_04.getValue()));
                break;
            }
            case 410 : // 410
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_COMPROMISO_05.getValue()));
                break;
            }
            case 370 : // 370
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 394 : // 394
            {
                value = (java.lang.Object)(((java.lang.Double)field_CD_ELEMENTO_04.getValue()));
                break;
            }
            case 403 : // 403
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 387 : // 387
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_ASIGANDO_03.getValue()));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 399 : // 399
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_COMPROMISO_04.getOldValue()));
                break;
            }
            case 392 : // 392
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 327 : // 327
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PRESUPUESTO.getOldValue()));
                break;
            }
            case 325 : // 325
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PRESUPUESTO.getOldValue()));
                break;
            }
            case 342 : // 342
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_COMPROMISO.getOldValue()));
                break;
            }
            case 423 : // 423
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_DESVIACION.getOldValue()));
                break;
            }
            case 408 : // 408
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PRESUPUESTO_05.getOldValue()));
                break;
            }
            case 367 : // 367
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_GASTADO_01.getOldValue()));
                break;
            }
            case 335 : // 335
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_ASIGNADO.getOldValue()));
                break;
            }
            case 361 : // 361
            {
                value = (java.lang.Object)(((java.lang.Double)field_CD_ELEMENTO_01.getOldValue()));
                break;
            }
            case 401 : // 401
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PAGO_04.getOldValue()));
                break;
            }
            case 317 : // 317
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 341 : // 341
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_COMPROMISO.getOldValue()));
                break;
            }
            case 369 : // 369
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_DESVIACION_01.getOldValue()));
                break;
            }
            case 347 : // 347
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_GASTADO.getOldValue()));
                break;
            }
            case 391 : // 391
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_DESVIACION_03.getOldValue()));
                break;
            }
            case 331 : // 331
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_ASIGNADO.getOldValue()));
                break;
            }
            case 380 : // 380
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_DESVIACION_02.getOldValue()));
                break;
            }
            case 360 : // 360
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_DESVIACION.getOldValue()));
                break;
            }
            case 353 : // 353
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PAGO.getOldValue()));
                break;
            }
            case 373 : // 373
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)parameter_P3.getValue()).intValue()<=((java.lang.Double)field_CD_TIPOELEMENTO_02.getOldValue()).intValue()));
                break;
            }
            case 349 : // 349
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PAGO.getOldValue()));
                break;
            }
            case 382 : // 382
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 419 : // 419
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_ASIGNADO.getOldValue()));
                break;
            }
            case 313 : // 313
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 402 : // 402
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_DESVIACION_04.getOldValue()));
                break;
            }
            case 406 : // 406
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)parameter_P3.getValue()).intValue()<=((java.lang.Double)field_CD_TIPOELEMENTO_05.getOldValue()).intValue()));
                break;
            }
            case 321 : // 321
            {
                value = (java.lang.String)(new String("Admin"));
                break;
            }
            case 388 : // 388
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_COMPROMISO_03.getOldValue()));
                break;
            }
            case 328 : // 328
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PRESUPUESTO.getOldValue()));
                break;
            }
            case 354 : // 354
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PAGO.getOldValue()));
                break;
            }
            case 422 : // 422
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PAGO.getOldValue()));
                break;
            }
            case 330 : // 330
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PRESUPUESTO.getOldValue()));
                break;
            }
            case 378 : // 378
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_GASTADO_02.getOldValue()));
                break;
            }
            case 348 : // 348
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_GASTADO.getOldValue()));
                break;
            }
            case 412 : // 412
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PAGO_05.getOldValue()));
                break;
            }
            case 420 : // 420
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_COMPROMISO.getOldValue()));
                break;
            }
            case 352 : // 352
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PAGO.getOldValue()));
                break;
            }
            case 417 : // 417
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_06.getOldValue()));
                break;
            }
            case 318 : // 318
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 375 : // 375
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PRESUPUESTO_02.getOldValue()));
                break;
            }
            case 371 : // 371
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 322 : // 322
            {
                value = (java.lang.Integer)(new Integer("2005"));
                break;
            }
            case 346 : // 346
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_GASTADO.getOldValue()));
                break;
            }
            case 424 : // 424
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()));
                break;
            }
            case 329 : // 329
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PRESUPUESTO.getOldValue()));
                break;
            }
            case 362 : // 362
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)parameter_P3.getValue()).intValue()<=((java.lang.Double)field_CD_TIPOELEMENTO_01.getOldValue()).intValue()));
                break;
            }
            case 343 : // 343
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_GASTADO.getOldValue()));
                break;
            }
            case 398 : // 398
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_ASIGANDO_04.getOldValue()));
                break;
            }
            case 404 : // 404
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 345 : // 345
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_GASTADO.getOldValue()));
                break;
            }
            case 357 : // 357
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_DESVIACION.getOldValue()));
                break;
            }
            case 397 : // 397
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PRESUPUESTO_04.getOldValue()));
                break;
            }
            case 358 : // 358
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_DESVIACION.getOldValue()));
                break;
            }
            case 351 : // 351
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PAGO.getOldValue()));
                break;
            }
            case 411 : // 411
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_GASTADO_05.getOldValue()));
                break;
            }
            case 326 : // 326
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PRESUPUESTO.getOldValue()));
                break;
            }
            case 365 : // 365
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_ASIGANDO_01.getOldValue()));
                break;
            }
            case 413 : // 413
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_DESVIACION_05.getOldValue()));
                break;
            }
            case 374 : // 374
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_02.getOldValue()));
                break;
            }
            case 356 : // 356
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_DESVIACION.getOldValue()));
                break;
            }
            case 350 : // 350
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PAGO.getOldValue()));
                break;
            }
            case 418 : // 418
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PRESUPUESTO.getOldValue()));
                break;
            }
            case 389 : // 389
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_GASTADO_03.getOldValue()));
                break;
            }
            case 338 : // 338
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_COMPROMISO.getOldValue()));
                break;
            }
            case 320 : // 320
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 332 : // 332
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_ASIGNADO.getOldValue()));
                break;
            }
            case 336 : // 336
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_ASIGNADO.getOldValue()));
                break;
            }
            case 393 : // 393
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 368 : // 368
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PAGO_01.getOldValue()));
                break;
            }
            case 355 : // 355
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_DESVIACION.getOldValue()));
                break;
            }
            case 381 : // 381
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 409 : // 409
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_ASIGANDO_05.getOldValue()));
                break;
            }
            case 339 : // 339
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_COMPROMISO.getOldValue()));
                break;
            }
            case 376 : // 376
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_ASIGANDO_02.getOldValue()));
                break;
            }
            case 407 : // 407
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_05.getOldValue()));
                break;
            }
            case 315 : // 315
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 383 : // 383
            {
                value = (java.lang.Object)(((java.lang.Double)field_CD_ELEMENTO_03.getOldValue()));
                break;
            }
            case 337 : // 337
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_COMPROMISO.getOldValue()));
                break;
            }
            case 416 : // 416
            {
                value = (java.lang.String)(java.util.Calendar.getInstance().get(java.util.Calendar.DATE)
+ "/" +
((java.util.Calendar.getInstance().get(java.util.Calendar.MONTH))+1)
+ "/" +
java.util.Calendar.getInstance().get(java.util.Calendar.YEAR));
                break;
            }
            case 384 : // 384
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)parameter_P3.getValue()).intValue()<=((java.lang.Double)field_CD_TIPOELEMENTO_03.getOldValue()).intValue()));
                break;
            }
            case 386 : // 386
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PRESUPUESTO_03.getOldValue()));
                break;
            }
            case 414 : // 414
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 405 : // 405
            {
                value = (java.lang.Object)(((java.lang.Double)field_CD_ELEMENTO_05.getOldValue()));
                break;
            }
            case 340 : // 340
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_COMPROMISO.getOldValue()));
                break;
            }
            case 314 : // 314
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 359 : // 359
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_DESVIACION.getOldValue()));
                break;
            }
            case 323 : // 323
            {
                value = (java.lang.Integer)(new Integer("2"));
                break;
            }
            case 377 : // 377
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_COMPROMISO_02.getOldValue()));
                break;
            }
            case 316 : // 316
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 324 : // 324
            {
                value = (java.lang.String)(new String("A1"));
                break;
            }
            case 421 : // 421
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_GASTADO.getOldValue()));
                break;
            }
            case 379 : // 379
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PAGO_02.getOldValue()));
                break;
            }
            case 425 : // 425
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()));
                break;
            }
            case 334 : // 334
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_ASIGNADO.getOldValue()));
                break;
            }
            case 415 : // 415
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 385 : // 385
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_03.getOldValue()));
                break;
            }
            case 333 : // 333
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_ASIGNADO.getOldValue()));
                break;
            }
            case 344 : // 344
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_GASTADO.getOldValue()));
                break;
            }
            case 363 : // 363
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_01.getOldValue()));
                break;
            }
           default :
           {
               value = evaluateOld1(id);
           }
        }
        
        return value;
    }


    /**
     *
     */
    private Object evaluateOld1(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 319 : // 319
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 396 : // 396
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_04.getOldValue()));
                break;
            }
            case 372 : // 372
            {
                value = (java.lang.Object)(((java.lang.Double)field_CD_ELEMENTO_02.getOldValue()));
                break;
            }
            case 364 : // 364
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PRESUPUESTO_01.getOldValue()));
                break;
            }
            case 390 : // 390
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PAGO_03.getOldValue()));
                break;
            }
            case 366 : // 366
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_COMPROMISO_01.getOldValue()));
                break;
            }
            case 395 : // 395
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)parameter_P3.getValue()).intValue()<=((java.lang.Double)field_CD_TIPOELEMENTO_04.getOldValue()).intValue()));
                break;
            }
            case 400 : // 400
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_GASTADO_04.getOldValue()));
                break;
            }
            case 410 : // 410
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_COMPROMISO_05.getOldValue()));
                break;
            }
            case 370 : // 370
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 394 : // 394
            {
                value = (java.lang.Object)(((java.lang.Double)field_CD_ELEMENTO_04.getOldValue()));
                break;
            }
            case 403 : // 403
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 387 : // 387
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_ASIGANDO_03.getOldValue()));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 399 : // 399
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_COMPROMISO_04.getEstimatedValue()));
                break;
            }
            case 392 : // 392
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 327 : // 327
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PRESUPUESTO.getValue()));
                break;
            }
            case 325 : // 325
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PRESUPUESTO.getValue()));
                break;
            }
            case 342 : // 342
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_COMPROMISO.getValue()));
                break;
            }
            case 423 : // 423
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_DESVIACION.getValue()));
                break;
            }
            case 408 : // 408
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PRESUPUESTO_05.getEstimatedValue()));
                break;
            }
            case 367 : // 367
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_GASTADO_01.getEstimatedValue()));
                break;
            }
            case 335 : // 335
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_ASIGNADO.getValue()));
                break;
            }
            case 361 : // 361
            {
                value = (java.lang.Object)(((java.lang.Double)field_CD_ELEMENTO_01.getValue()));
                break;
            }
            case 401 : // 401
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PAGO_04.getEstimatedValue()));
                break;
            }
            case 317 : // 317
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 341 : // 341
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_COMPROMISO.getValue()));
                break;
            }
            case 369 : // 369
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_DESVIACION_01.getEstimatedValue()));
                break;
            }
            case 347 : // 347
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_GASTADO.getValue()));
                break;
            }
            case 391 : // 391
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_DESVIACION_03.getEstimatedValue()));
                break;
            }
            case 331 : // 331
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_ASIGNADO.getValue()));
                break;
            }
            case 380 : // 380
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_DESVIACION_02.getEstimatedValue()));
                break;
            }
            case 360 : // 360
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_DESVIACION.getValue()));
                break;
            }
            case 353 : // 353
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PAGO.getValue()));
                break;
            }
            case 373 : // 373
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)parameter_P3.getValue()).intValue()<=((java.lang.Double)field_CD_TIPOELEMENTO_02.getValue()).intValue()));
                break;
            }
            case 349 : // 349
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PAGO.getValue()));
                break;
            }
            case 382 : // 382
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 419 : // 419
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_ASIGNADO.getValue()));
                break;
            }
            case 313 : // 313
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 402 : // 402
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_DESVIACION_04.getEstimatedValue()));
                break;
            }
            case 406 : // 406
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)parameter_P3.getValue()).intValue()<=((java.lang.Double)field_CD_TIPOELEMENTO_05.getValue()).intValue()));
                break;
            }
            case 321 : // 321
            {
                value = (java.lang.String)(new String("Admin"));
                break;
            }
            case 388 : // 388
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_COMPROMISO_03.getEstimatedValue()));
                break;
            }
            case 328 : // 328
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PRESUPUESTO.getValue()));
                break;
            }
            case 354 : // 354
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PAGO.getValue()));
                break;
            }
            case 422 : // 422
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PAGO.getValue()));
                break;
            }
            case 330 : // 330
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PRESUPUESTO.getValue()));
                break;
            }
            case 378 : // 378
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_GASTADO_02.getEstimatedValue()));
                break;
            }
            case 348 : // 348
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_GASTADO.getValue()));
                break;
            }
            case 412 : // 412
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PAGO_05.getEstimatedValue()));
                break;
            }
            case 420 : // 420
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_COMPROMISO.getValue()));
                break;
            }
            case 352 : // 352
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PAGO.getValue()));
                break;
            }
            case 417 : // 417
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_06.getValue()));
                break;
            }
            case 318 : // 318
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 375 : // 375
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PRESUPUESTO_02.getEstimatedValue()));
                break;
            }
            case 371 : // 371
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 322 : // 322
            {
                value = (java.lang.Integer)(new Integer("2005"));
                break;
            }
            case 346 : // 346
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_GASTADO.getValue()));
                break;
            }
            case 424 : // 424
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()));
                break;
            }
            case 329 : // 329
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PRESUPUESTO.getValue()));
                break;
            }
            case 362 : // 362
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)parameter_P3.getValue()).intValue()<=((java.lang.Double)field_CD_TIPOELEMENTO_01.getValue()).intValue()));
                break;
            }
            case 343 : // 343
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_GASTADO.getValue()));
                break;
            }
            case 398 : // 398
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_ASIGANDO_04.getEstimatedValue()));
                break;
            }
            case 404 : // 404
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 345 : // 345
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_GASTADO.getValue()));
                break;
            }
            case 357 : // 357
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_DESVIACION.getValue()));
                break;
            }
            case 397 : // 397
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PRESUPUESTO_04.getEstimatedValue()));
                break;
            }
            case 358 : // 358
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_DESVIACION.getValue()));
                break;
            }
            case 351 : // 351
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PAGO.getValue()));
                break;
            }
            case 411 : // 411
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_GASTADO_05.getEstimatedValue()));
                break;
            }
            case 326 : // 326
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PRESUPUESTO.getValue()));
                break;
            }
            case 365 : // 365
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_ASIGANDO_01.getEstimatedValue()));
                break;
            }
            case 413 : // 413
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_DESVIACION_05.getEstimatedValue()));
                break;
            }
            case 374 : // 374
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_02.getValue()));
                break;
            }
            case 356 : // 356
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_DESVIACION.getValue()));
                break;
            }
            case 350 : // 350
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PAGO.getValue()));
                break;
            }
            case 418 : // 418
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PRESUPUESTO.getValue()));
                break;
            }
            case 389 : // 389
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_GASTADO_03.getEstimatedValue()));
                break;
            }
            case 338 : // 338
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_COMPROMISO.getValue()));
                break;
            }
            case 320 : // 320
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 332 : // 332
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_ASIGNADO.getValue()));
                break;
            }
            case 336 : // 336
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_ASIGNADO.getValue()));
                break;
            }
            case 393 : // 393
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 368 : // 368
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PAGO_01.getEstimatedValue()));
                break;
            }
            case 355 : // 355
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_DESVIACION.getValue()));
                break;
            }
            case 381 : // 381
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 409 : // 409
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_ASIGANDO_05.getEstimatedValue()));
                break;
            }
            case 339 : // 339
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_COMPROMISO.getValue()));
                break;
            }
            case 376 : // 376
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_ASIGANDO_02.getEstimatedValue()));
                break;
            }
            case 407 : // 407
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_05.getValue()));
                break;
            }
            case 315 : // 315
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 383 : // 383
            {
                value = (java.lang.Object)(((java.lang.Double)field_CD_ELEMENTO_03.getValue()));
                break;
            }
            case 337 : // 337
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_COMPROMISO.getValue()));
                break;
            }
            case 416 : // 416
            {
                value = (java.lang.String)(java.util.Calendar.getInstance().get(java.util.Calendar.DATE)
+ "/" +
((java.util.Calendar.getInstance().get(java.util.Calendar.MONTH))+1)
+ "/" +
java.util.Calendar.getInstance().get(java.util.Calendar.YEAR));
                break;
            }
            case 384 : // 384
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)parameter_P3.getValue()).intValue()<=((java.lang.Double)field_CD_TIPOELEMENTO_03.getValue()).intValue()));
                break;
            }
            case 386 : // 386
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PRESUPUESTO_03.getEstimatedValue()));
                break;
            }
            case 414 : // 414
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 405 : // 405
            {
                value = (java.lang.Object)(((java.lang.Double)field_CD_ELEMENTO_05.getValue()));
                break;
            }
            case 340 : // 340
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_COMPROMISO.getValue()));
                break;
            }
            case 314 : // 314
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 359 : // 359
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_DESVIACION.getValue()));
                break;
            }
            case 323 : // 323
            {
                value = (java.lang.Integer)(new Integer("2"));
                break;
            }
            case 377 : // 377
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_COMPROMISO_02.getEstimatedValue()));
                break;
            }
            case 316 : // 316
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 324 : // 324
            {
                value = (java.lang.String)(new String("A1"));
                break;
            }
            case 421 : // 421
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_GASTADO.getValue()));
                break;
            }
            case 379 : // 379
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PAGO_02.getEstimatedValue()));
                break;
            }
            case 425 : // 425
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()));
                break;
            }
            case 334 : // 334
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_ASIGNADO.getValue()));
                break;
            }
            case 415 : // 415
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 385 : // 385
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_03.getValue()));
                break;
            }
            case 333 : // 333
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_ASIGNADO.getValue()));
                break;
            }
            case 344 : // 344
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_GASTADO.getValue()));
                break;
            }
            case 363 : // 363
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_01.getValue()));
                break;
            }
           default :
           {
               value = evaluateEstimated1(id);
           }
        }
        
        return value;
    }


    /**
     *
     */
    private Object evaluateEstimated1(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 319 : // 319
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 396 : // 396
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_04.getValue()));
                break;
            }
            case 372 : // 372
            {
                value = (java.lang.Object)(((java.lang.Double)field_CD_ELEMENTO_02.getValue()));
                break;
            }
            case 364 : // 364
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PRESUPUESTO_01.getEstimatedValue()));
                break;
            }
            case 390 : // 390
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PAGO_03.getEstimatedValue()));
                break;
            }
            case 366 : // 366
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_COMPROMISO_01.getEstimatedValue()));
                break;
            }
            case 395 : // 395
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)parameter_P3.getValue()).intValue()<=((java.lang.Double)field_CD_TIPOELEMENTO_04.getValue()).intValue()));
                break;
            }
            case 400 : // 400
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_GASTADO_04.getEstimatedValue()));
                break;
            }
            case 410 : // 410
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_COMPROMISO_05.getEstimatedValue()));
                break;
            }
            case 370 : // 370
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 394 : // 394
            {
                value = (java.lang.Object)(((java.lang.Double)field_CD_ELEMENTO_04.getValue()));
                break;
            }
            case 403 : // 403
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 387 : // 387
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_ASIGANDO_03.getEstimatedValue()));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
