/*
 * Generated by JasperReports - 4/08/08 11:59
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;

import java.util.*;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.data.*;


/**
 *
 */
public class RPT_168 extends JRCalculator
{


    /**
     *
     */
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillParameter parameter_P1 = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_P4 = null;
    private JRFillParameter parameter_P2 = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillParameter parameter_P3 = null;
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;

    private JRFillField field_IMP_DESVIACION = null;
    private JRFillField field_CD_ELEMENTO_02 = null;
    private JRFillField field_DS_ELEMENTO_04 = null;
    private JRFillField field_CD_ELEMENTO_05 = null;
    private JRFillField field_CD_TIPOELEMENTO_02 = null;
    private JRFillField field_CD_TIPOELEMENTO_05 = null;
    private JRFillField field_IMP_COMPROMISO = null;
    private JRFillField field_DS_ELEMENTO_01 = null;
    private JRFillField field_CD_ELEMENTO_03 = null;
    private JRFillField field_CD_TIPOELEMENTO_01 = null;
    private JRFillField field_DS_ELEMENTO_06 = null;
    private JRFillField field_CD_ELEMENTO_04 = null;
    private JRFillField field_CD_TIPOELEMENTO_04 = null;
    private JRFillField field_DS_ELEMENTO_02 = null;
    private JRFillField field_IMP_ASIGNADO = null;
    private JRFillField field_IMP_PRESUPUESTO = null;
    private JRFillField field_CD_TIPOELEMENTO_03 = null;
    private JRFillField field_DS_ELEMENTO_05 = null;
    private JRFillField field_IMP_PAGO = null;
    private JRFillField field_IMP_GASTADO = null;
    private JRFillField field_CD_ELEMENTO_01 = null;
    private JRFillField field_CD_ELEMENTO_06 = null;
    private JRFillField field_DS_ELEMENTO_03 = null;
    private JRFillField field_CD_TIPOELEMENTO_06 = null;

    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_SUM_IMP_PRESUPUESTO_01 = null;
    private JRFillVariable variable_SUM_IMP_PRESUPUESTO_02 = null;
    private JRFillVariable variable_SUM_IMP_PRESUPUESTO_03 = null;
    private JRFillVariable variable_SUM_IMP_PRESUPUESTO_04 = null;
    private JRFillVariable variable_SUM_IMP_PRESUPUESTO_05 = null;
    private JRFillVariable variable_SUM_IMP_PRESUPUESTO_06 = null;
    private JRFillVariable variable_SUM_IMP_ASIGANDO_01 = null;
    private JRFillVariable variable_SUM_IMP_ASIGANDO_02 = null;
    private JRFillVariable variable_SUM_IMP_ASIGANDO_03 = null;
    private JRFillVariable variable_SUM_IMP_ASIGANDO_04 = null;
    private JRFillVariable variable_SUM_IMP_ASIGANDO_05 = null;
    private JRFillVariable variable_SUM_IMP_ASIGANDO_06 = null;
    private JRFillVariable variable_SUM_IMP_COMPROMISO_01 = null;
    private JRFillVariable variable_SUM_IMP_COMPROMISO_02 = null;
    private JRFillVariable variable_SUM_IMP_COMPROMISO_03 = null;
    private JRFillVariable variable_SUM_IMP_COMPROMISO_04 = null;
    private JRFillVariable variable_SUM_IMP_COMPROMISO_05 = null;
    private JRFillVariable variable_SUM_IMP_COMPROMISO_06 = null;
    private JRFillVariable variable_SUM_IMP_GASTADO_01 = null;
    private JRFillVariable variable_SUM_IMP_GASTADO_02 = null;
    private JRFillVariable variable_SUM_IMP_GASTADO_03 = null;
    private JRFillVariable variable_SUM_IMP_GASTADO_04 = null;
    private JRFillVariable variable_SUM_IMP_GASTADO_05 = null;
    private JRFillVariable variable_SUM_IMP_GASTADO_06 = null;
    private JRFillVariable variable_SUM_IMP_PAGO_01 = null;
    private JRFillVariable variable_SUM_IMP_PAGO_02 = null;
    private JRFillVariable variable_SUM_IMP_PAGO_03 = null;
    private JRFillVariable variable_SUM_IMP_PAGO_04 = null;
    private JRFillVariable variable_SUM_IMP_PAGO_05 = null;
    private JRFillVariable variable_SUM_IMP_PAGO_06 = null;
    private JRFillVariable variable_SUM_IMP_DESVIACION_01 = null;
    private JRFillVariable variable_SUM_IMP_DESVIACION_02 = null;
    private JRFillVariable variable_SUM_IMP_DESVIACION_03 = null;
    private JRFillVariable variable_SUM_IMP_DESVIACION_04 = null;
    private JRFillVariable variable_SUM_IMP_DESVIACION_05 = null;
    private JRFillVariable variable_SUM_IMP_DESVIACION_06 = null;
    private JRFillVariable variable_Grupo_Compañia_COUNT = null;
    private JRFillVariable variable_Grupo_Area_COUNT = null;
    private JRFillVariable variable_Grupo_Programa_COUNT = null;
    private JRFillVariable variable_Grupo_Subprograma_COUNT = null;
    private JRFillVariable variable_Grupo_Espacio_COUNT = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
        parameter_P1 = (JRFillParameter)pm.get("P1");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_P4 = (JRFillParameter)pm.get("P4");
        parameter_P2 = (JRFillParameter)pm.get("P2");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
        parameter_P3 = (JRFillParameter)pm.get("P3");
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
        field_IMP_DESVIACION = (JRFillField)fm.get("IMP_DESVIACION");
        field_CD_ELEMENTO_02 = (JRFillField)fm.get("CD_ELEMENTO_02");
        field_DS_ELEMENTO_04 = (JRFillField)fm.get("DS_ELEMENTO_04");
        field_CD_ELEMENTO_05 = (JRFillField)fm.get("CD_ELEMENTO_05");
        field_CD_TIPOELEMENTO_02 = (JRFillField)fm.get("CD_TIPOELEMENTO_02");
        field_CD_TIPOELEMENTO_05 = (JRFillField)fm.get("CD_TIPOELEMENTO_05");
        field_IMP_COMPROMISO = (JRFillField)fm.get("IMP_COMPROMISO");
        field_DS_ELEMENTO_01 = (JRFillField)fm.get("DS_ELEMENTO_01");
        field_CD_ELEMENTO_03 = (JRFillField)fm.get("CD_ELEMENTO_03");
        field_CD_TIPOELEMENTO_01 = (JRFillField)fm.get("CD_TIPOELEMENTO_01");
        field_DS_ELEMENTO_06 = (JRFillField)fm.get("DS_ELEMENTO_06");
        field_CD_ELEMENTO_04 = (JRFillField)fm.get("CD_ELEMENTO_04");
        field_CD_TIPOELEMENTO_04 = (JRFillField)fm.get("CD_TIPOELEMENTO_04");
        field_DS_ELEMENTO_02 = (JRFillField)fm.get("DS_ELEMENTO_02");
        field_IMP_ASIGNADO = (JRFillField)fm.get("IMP_ASIGNADO");
        field_IMP_PRESUPUESTO = (JRFillField)fm.get("IMP_PRESUPUESTO");
        field_CD_TIPOELEMENTO_03 = (JRFillField)fm.get("CD_TIPOELEMENTO_03");
        field_DS_ELEMENTO_05 = (JRFillField)fm.get("DS_ELEMENTO_05");
        field_IMP_PAGO = (JRFillField)fm.get("IMP_PAGO");
        field_IMP_GASTADO = (JRFillField)fm.get("IMP_GASTADO");
        field_CD_ELEMENTO_01 = (JRFillField)fm.get("CD_ELEMENTO_01");
        field_CD_ELEMENTO_06 = (JRFillField)fm.get("CD_ELEMENTO_06");
        field_DS_ELEMENTO_03 = (JRFillField)fm.get("DS_ELEMENTO_03");
        field_CD_TIPOELEMENTO_06 = (JRFillField)fm.get("CD_TIPOELEMENTO_06");
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
        variable_SUM_IMP_PRESUPUESTO_01 = (JRFillVariable)vm.get("SUM_IMP_PRESUPUESTO_01");
        variable_SUM_IMP_PRESUPUESTO_02 = (JRFillVariable)vm.get("SUM_IMP_PRESUPUESTO_02");
        variable_SUM_IMP_PRESUPUESTO_03 = (JRFillVariable)vm.get("SUM_IMP_PRESUPUESTO_03");
        variable_SUM_IMP_PRESUPUESTO_04 = (JRFillVariable)vm.get("SUM_IMP_PRESUPUESTO_04");
        variable_SUM_IMP_PRESUPUESTO_05 = (JRFillVariable)vm.get("SUM_IMP_PRESUPUESTO_05");
        variable_SUM_IMP_PRESUPUESTO_06 = (JRFillVariable)vm.get("SUM_IMP_PRESUPUESTO_06");
        variable_SUM_IMP_ASIGANDO_01 = (JRFillVariable)vm.get("SUM_IMP_ASIGANDO_01");
        variable_SUM_IMP_ASIGANDO_02 = (JRFillVariable)vm.get("SUM_IMP_ASIGANDO_02");
        variable_SUM_IMP_ASIGANDO_03 = (JRFillVariable)vm.get("SUM_IMP_ASIGANDO_03");
        variable_SUM_IMP_ASIGANDO_04 = (JRFillVariable)vm.get("SUM_IMP_ASIGANDO_04");
        variable_SUM_IMP_ASIGANDO_05 = (JRFillVariable)vm.get("SUM_IMP_ASIGANDO_05");
        variable_SUM_IMP_ASIGANDO_06 = (JRFillVariable)vm.get("SUM_IMP_ASIGANDO_06");
        variable_SUM_IMP_COMPROMISO_01 = (JRFillVariable)vm.get("SUM_IMP_COMPROMISO_01");
        variable_SUM_IMP_COMPROMISO_02 = (JRFillVariable)vm.get("SUM_IMP_COMPROMISO_02");
        variable_SUM_IMP_COMPROMISO_03 = (JRFillVariable)vm.get("SUM_IMP_COMPROMISO_03");
        variable_SUM_IMP_COMPROMISO_04 = (JRFillVariable)vm.get("SUM_IMP_COMPROMISO_04");
        variable_SUM_IMP_COMPROMISO_05 = (JRFillVariable)vm.get("SUM_IMP_COMPROMISO_05");
        variable_SUM_IMP_COMPROMISO_06 = (JRFillVariable)vm.get("SUM_IMP_COMPROMISO_06");
        variable_SUM_IMP_GASTADO_01 = (JRFillVariable)vm.get("SUM_IMP_GASTADO_01");
        variable_SUM_IMP_GASTADO_02 = (JRFillVariable)vm.get("SUM_IMP_GASTADO_02");
        variable_SUM_IMP_GASTADO_03 = (JRFillVariable)vm.get("SUM_IMP_GASTADO_03");
        variable_SUM_IMP_GASTADO_04 = (JRFillVariable)vm.get("SUM_IMP_GASTADO_04");
        variable_SUM_IMP_GASTADO_05 = (JRFillVariable)vm.get("SUM_IMP_GASTADO_05");
        variable_SUM_IMP_GASTADO_06 = (JRFillVariable)vm.get("SUM_IMP_GASTADO_06");
        variable_SUM_IMP_PAGO_01 = (JRFillVariable)vm.get("SUM_IMP_PAGO_01");
        variable_SUM_IMP_PAGO_02 = (JRFillVariable)vm.get("SUM_IMP_PAGO_02");
        variable_SUM_IMP_PAGO_03 = (JRFillVariable)vm.get("SUM_IMP_PAGO_03");
        variable_SUM_IMP_PAGO_04 = (JRFillVariable)vm.get("SUM_IMP_PAGO_04");
        variable_SUM_IMP_PAGO_05 = (JRFillVariable)vm.get("SUM_IMP_PAGO_05");
        variable_SUM_IMP_PAGO_06 = (JRFillVariable)vm.get("SUM_IMP_PAGO_06");
        variable_SUM_IMP_DESVIACION_01 = (JRFillVariable)vm.get("SUM_IMP_DESVIACION_01");
        variable_SUM_IMP_DESVIACION_02 = (JRFillVariable)vm.get("SUM_IMP_DESVIACION_02");
        variable_SUM_IMP_DESVIACION_03 = (JRFillVariable)vm.get("SUM_IMP_DESVIACION_03");
        variable_SUM_IMP_DESVIACION_04 = (JRFillVariable)vm.get("SUM_IMP_DESVIACION_04");
        variable_SUM_IMP_DESVIACION_05 = (JRFillVariable)vm.get("SUM_IMP_DESVIACION_05");
        variable_SUM_IMP_DESVIACION_06 = (JRFillVariable)vm.get("SUM_IMP_DESVIACION_06");
        variable_Grupo_Compañia_COUNT = (JRFillVariable)vm.get("Grupo_Compañia_COUNT");
        variable_Grupo_Area_COUNT = (JRFillVariable)vm.get("Grupo_Area_COUNT");
        variable_Grupo_Programa_COUNT = (JRFillVariable)vm.get("Grupo_Programa_COUNT");
        variable_Grupo_Subprograma_COUNT = (JRFillVariable)vm.get("Grupo_Subprograma_COUNT");
        variable_Grupo_Espacio_COUNT = (JRFillVariable)vm.get("Grupo_Espacio_COUNT");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 27 : // 27
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_COMPROMISO.getValue()));
                break;
            }
            case 98 : // 98
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_GASTADO_05.getValue()));
                break;
            }
            case 34 : // 34
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_GASTADO.getValue()));
                break;
            }
            case 111 : // 111
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getValue()));
                break;
            }
            case 26 : // 26
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_COMPROMISO.getValue()));
                break;
            }
            case 48 : // 48
            {
                value = (java.lang.Object)(((java.lang.Double)field_CD_ELEMENTO_01.getValue()));
                break;
            }
            case 49 : // 49
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)parameter_P3.getValue()).intValue()<=((java.lang.Double)field_CD_TIPOELEMENTO_01.getValue()).intValue()));
                break;
            }
            case 104 : // 104
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_06.getValue()));
                break;
            }
            case 40 : // 40
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PAGO.getValue()));
                break;
            }
            case 57 : // 57
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 31 : // 31
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_GASTADO.getValue()));
                break;
            }
            case 23 : // 23
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_ASIGNADO.getValue()));
                break;
            }
            case 109 : // 109
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PAGO.getValue()));
                break;
            }
            case 106 : // 106
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_ASIGNADO.getValue()));
                break;
            }
            case 13 : // 13
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PRESUPUESTO.getValue()));
                break;
            }
            case 62 : // 62
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PRESUPUESTO_02.getValue()));
                break;
            }
            case 56 : // 56
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_DESVIACION_01.getValue()));
                break;
            }
            case 60 : // 60
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)parameter_P3.getValue()).intValue()<=((java.lang.Double)field_CD_TIPOELEMENTO_02.getValue()).intValue()));
                break;
            }
            case 95 : // 95
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PRESUPUESTO_05.getValue()));
                break;
            }
            case 16 : // 16
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PRESUPUESTO.getValue()));
                break;
            }
            case 100 : // 100
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_DESVIACION_05.getValue()));
                break;
            }
            case 68 : // 68
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 99 : // 99
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PAGO_05.getValue()));
                break;
            }
            case 22 : // 22
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_ASIGNADO.getValue()));
                break;
            }
            case 79 : // 79
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 33 : // 33
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_GASTADO.getValue()));
                break;
            }
            case 41 : // 41
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PAGO.getValue()));
                break;
            }
            case 50 : // 50
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_01.getValue()));
                break;
            }
            case 70 : // 70
            {
                value = (java.lang.Object)(((java.lang.Double)field_CD_ELEMENTO_03.getValue()));
                break;
            }
            case 107 : // 107
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_COMPROMISO.getValue()));
                break;
            }
            case 74 : // 74
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_ASIGANDO_03.getValue()));
                break;
            }
            case 54 : // 54
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_GASTADO_01.getValue()));
                break;
            }
            case 53 : // 53
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_COMPROMISO_01.getValue()));
                break;
            }
            case 44 : // 44
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_DESVIACION.getValue()));
                break;
            }
            case 51 : // 51
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PRESUPUESTO_01.getValue()));
                break;
            }
            case 38 : // 38
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PAGO.getValue()));
                break;
            }
            case 35 : // 35
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_GASTADO.getValue()));
                break;
            }
            case 8 : // 8
            {
                value = (java.lang.String)(new String("Admin"));
                break;
            }
            case 73 : // 73
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PRESUPUESTO_03.getValue()));
                break;
            }
            case 83 : // 83
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_04.getValue()));
                break;
            }
            case 94 : // 94
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_05.getValue()));
                break;
            }
            case 97 : // 97
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_COMPROMISO_05.getValue()));
                break;
            }
            case 15 : // 15
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PRESUPUESTO.getValue()));
                break;
            }
            case 12 : // 12
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PRESUPUESTO.getValue()));
                break;
            }
            case 3 : // 3
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 101 : // 101
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 108 : // 108
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_GASTADO.getValue()));
                break;
            }
            case 14 : // 14
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PRESUPUESTO.getValue()));
                break;
            }
            case 10 : // 10
            {
                value = (java.lang.Integer)(new Integer("2"));
                break;
            }
            case 18 : // 18
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_ASIGNADO.getValue()));
                break;
            }
            case 19 : // 19
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_ASIGNADO.getValue()));
                break;
            }
            case 7 : // 7
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 91 : // 91
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 86 : // 86
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_COMPROMISO_04.getValue()));
                break;
            }
            case 76 : // 76
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_GASTADO_03.getValue()));
                break;
            }
            case 17 : // 17
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PRESUPUESTO.getValue()));
                break;
            }
            case 43 : // 43
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_DESVIACION.getValue()));
                break;
            }
            case 92 : // 92
            {
                value = (java.lang.Object)(((java.lang.Double)field_CD_ELEMENTO_05.getValue()));
                break;
            }
            case 1 : // 1
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 63 : // 63
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_ASIGANDO_02.getValue()));
                break;
            }
            case 28 : // 28
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_COMPROMISO.getValue()));
                break;
            }
            case 75 : // 75
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_COMPROMISO_03.getValue()));
                break;
            }
            case 105 : // 105
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PRESUPUESTO.getValue()));
                break;
            }
            case 39 : // 39
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PAGO.getValue()));
                break;
            }
            case 69 : // 69
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 37 : // 37
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PAGO.getValue()));
                break;
            }
            case 87 : // 87
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_GASTADO_04.getValue()));
                break;
            }
            case 4 : // 4
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 6 : // 6
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 71 : // 71
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)parameter_P3.getValue()).intValue()<=((java.lang.Double)field_CD_TIPOELEMENTO_03.getValue()).intValue()));
                break;
            }
            case 84 : // 84
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PRESUPUESTO_04.getValue()));
                break;
            }
            case 25 : // 25
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_COMPROMISO.getValue()));
                break;
            }
            case 5 : // 5
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 110 : // 110
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_DESVIACION.getValue()));
                break;
            }
            case 9 : // 9
            {
                value = (java.lang.Integer)(new Integer("2008"));
                break;
            }
            case 24 : // 24
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_COMPROMISO.getValue()));
                break;
            }
            case 93 : // 93
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)parameter_P3.getValue()).intValue()<=((java.lang.Double)field_CD_TIPOELEMENTO_05.getValue()).intValue()));
                break;
            }
            case 11 : // 11
            {
                value = (java.lang.String)(new String("A4"));
                break;
            }
            case 85 : // 85
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_ASIGANDO_04.getValue()));
                break;
            }
            case 81 : // 81
            {
                value = (java.lang.Object)(((java.lang.Double)field_CD_ELEMENTO_04.getValue()));
                break;
            }
            case 29 : // 29
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_COMPROMISO.getValue()));
                break;
            }
            case 47 : // 47
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_DESVIACION.getValue()));
                break;
            }
            case 72 : // 72
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_03.getValue()));
                break;
            }
            case 102 : // 102
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 0 : // 0
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 58 : // 58
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 67 : // 67
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_DESVIACION_02.getValue()));
                break;
            }
            case 55 : // 55
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PAGO_01.getValue()));
                break;
            }
            case 59 : // 59
            {
                value = (java.lang.Object)(((java.lang.Double)field_CD_ELEMENTO_02.getValue()));
                break;
            }
            case 82 : // 82
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)parameter_P3.getValue()).intValue()<=((java.lang.Double)field_CD_TIPOELEMENTO_04.getValue()).intValue()));
                break;
            }
            case 66 : // 66
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PAGO_02.getValue()));
                break;
            }
            case 88 : // 88
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PAGO_04.getValue()));
                break;
            }
            case 80 : // 80
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 20 : // 20
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_ASIGNADO.getValue()));
                break;
            }
            case 112 : // 112
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getValue()));
                break;
            }
            case 64 : // 64
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_COMPROMISO_02.getValue()));
                break;
            }
            case 32 : // 32
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_GASTADO.getValue()));
                break;
            }
            case 77 : // 77
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PAGO_03.getValue()));
                break;
            }
            case 65 : // 65
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_GASTADO_02.getValue()));
                break;
            }
            case 103 : // 103
            {
                value = (java.lang.String)(java.util.Calendar.getInstance().get(java.util.Calendar.DATE)
+ "/" +
((java.util.Calendar.getInstance().get(java.util.Calendar.MONTH))+1)
+ "/" +
java.util.Calendar.getInstance().get(java.util.Calendar.YEAR));
                break;
            }
           default :
           {
               value = evaluate1(id);
           }
        }
        
        return value;
    }


    /**
     *
     */
    private Object evaluate1(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 30 : // 30
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_GASTADO.getValue()));
                break;
            }
            case 21 : // 21
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_ASIGNADO.getValue()));
                break;
            }
            case 90 : // 90
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 61 : // 61
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_02.getValue()));
                break;
            }
            case 96 : // 96
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_ASIGANDO_05.getValue()));
                break;
            }
            case 52 : // 52
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_ASIGANDO_01.getValue()));
                break;
            }
            case 46 : // 46
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_DESVIACION.getValue()));
                break;
            }
            case 2 : // 2
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 45 : // 45
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_DESVIACION.getValue()));
                break;
            }
            case 36 : // 36
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PAGO.getValue()));
                break;
            }
            case 89 : // 89
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_DESVIACION_04.getValue()));
                break;
            }
            case 78 : // 78
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_DESVIACION_03.getValue()));
                break;
            }
            case 42 : // 42
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_DESVIACION.getValue()));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 27 : // 27
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_COMPROMISO.getOldValue()));
                break;
            }
            case 98 : // 98
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_GASTADO_05.getOldValue()));
                break;
            }
            case 34 : // 34
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_GASTADO.getOldValue()));
                break;
            }
            case 111 : // 111
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()));
                break;
            }
            case 26 : // 26
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_COMPROMISO.getOldValue()));
                break;
            }
            case 48 : // 48
            {
                value = (java.lang.Object)(((java.lang.Double)field_CD_ELEMENTO_01.getOldValue()));
                break;
            }
            case 49 : // 49
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)parameter_P3.getValue()).intValue()<=((java.lang.Double)field_CD_TIPOELEMENTO_01.getOldValue()).intValue()));
                break;
            }
            case 104 : // 104
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_06.getOldValue()));
                break;
            }
            case 40 : // 40
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PAGO.getOldValue()));
                break;
            }
            case 57 : // 57
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 31 : // 31
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_GASTADO.getOldValue()));
                break;
            }
            case 23 : // 23
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_ASIGNADO.getOldValue()));
                break;
            }
            case 109 : // 109
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PAGO.getOldValue()));
                break;
            }
            case 106 : // 106
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_ASIGNADO.getOldValue()));
                break;
            }
            case 13 : // 13
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PRESUPUESTO.getOldValue()));
                break;
            }
            case 62 : // 62
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PRESUPUESTO_02.getOldValue()));
                break;
            }
            case 56 : // 56
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_DESVIACION_01.getOldValue()));
                break;
            }
            case 60 : // 60
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)parameter_P3.getValue()).intValue()<=((java.lang.Double)field_CD_TIPOELEMENTO_02.getOldValue()).intValue()));
                break;
            }
            case 95 : // 95
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PRESUPUESTO_05.getOldValue()));
                break;
            }
            case 16 : // 16
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PRESUPUESTO.getOldValue()));
                break;
            }
            case 100 : // 100
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_DESVIACION_05.getOldValue()));
                break;
            }
            case 68 : // 68
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 99 : // 99
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PAGO_05.getOldValue()));
                break;
            }
            case 22 : // 22
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_ASIGNADO.getOldValue()));
                break;
            }
            case 79 : // 79
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 33 : // 33
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_GASTADO.getOldValue()));
                break;
            }
            case 41 : // 41
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PAGO.getOldValue()));
                break;
            }
            case 50 : // 50
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_01.getOldValue()));
                break;
            }
            case 70 : // 70
            {
                value = (java.lang.Object)(((java.lang.Double)field_CD_ELEMENTO_03.getOldValue()));
                break;
            }
            case 107 : // 107
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_COMPROMISO.getOldValue()));
                break;
            }
            case 74 : // 74
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_ASIGANDO_03.getOldValue()));
                break;
            }
            case 54 : // 54
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_GASTADO_01.getOldValue()));
                break;
            }
            case 53 : // 53
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_COMPROMISO_01.getOldValue()));
                break;
            }
            case 44 : // 44
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_DESVIACION.getOldValue()));
                break;
            }
            case 51 : // 51
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PRESUPUESTO_01.getOldValue()));
                break;
            }
            case 38 : // 38
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PAGO.getOldValue()));
                break;
            }
            case 35 : // 35
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_GASTADO.getOldValue()));
                break;
            }
            case 8 : // 8
            {
                value = (java.lang.String)(new String("Admin"));
                break;
            }
            case 73 : // 73
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PRESUPUESTO_03.getOldValue()));
                break;
            }
            case 83 : // 83
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_04.getOldValue()));
                break;
            }
            case 94 : // 94
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_05.getOldValue()));
                break;
            }
            case 97 : // 97
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_COMPROMISO_05.getOldValue()));
                break;
            }
            case 15 : // 15
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PRESUPUESTO.getOldValue()));
                break;
            }
            case 12 : // 12
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PRESUPUESTO.getOldValue()));
                break;
            }
            case 3 : // 3
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 101 : // 101
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 108 : // 108
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_GASTADO.getOldValue()));
                break;
            }
            case 14 : // 14
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PRESUPUESTO.getOldValue()));
                break;
            }
            case 10 : // 10
            {
                value = (java.lang.Integer)(new Integer("2"));
                break;
            }
            case 18 : // 18
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_ASIGNADO.getOldValue()));
                break;
            }
            case 19 : // 19
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_ASIGNADO.getOldValue()));
                break;
            }
            case 7 : // 7
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 91 : // 91
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 86 : // 86
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_COMPROMISO_04.getOldValue()));
                break;
            }
            case 76 : // 76
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_GASTADO_03.getOldValue()));
                break;
            }
            case 17 : // 17
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PRESUPUESTO.getOldValue()));
                break;
            }
            case 43 : // 43
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_DESVIACION.getOldValue()));
                break;
            }
            case 92 : // 92
            {
                value = (java.lang.Object)(((java.lang.Double)field_CD_ELEMENTO_05.getOldValue()));
                break;
            }
            case 1 : // 1
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 63 : // 63
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_ASIGANDO_02.getOldValue()));
                break;
            }
            case 28 : // 28
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_COMPROMISO.getOldValue()));
                break;
            }
            case 75 : // 75
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_COMPROMISO_03.getOldValue()));
                break;
            }
            case 105 : // 105
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PRESUPUESTO.getOldValue()));
                break;
            }
            case 39 : // 39
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PAGO.getOldValue()));
                break;
            }
            case 69 : // 69
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 37 : // 37
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PAGO.getOldValue()));
                break;
            }
            case 87 : // 87
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_GASTADO_04.getOldValue()));
                break;
            }
            case 4 : // 4
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 6 : // 6
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 71 : // 71
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)parameter_P3.getValue()).intValue()<=((java.lang.Double)field_CD_TIPOELEMENTO_03.getOldValue()).intValue()));
                break;
            }
            case 84 : // 84
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PRESUPUESTO_04.getOldValue()));
                break;
            }
            case 25 : // 25
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_COMPROMISO.getOldValue()));
                break;
            }
            case 5 : // 5
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 110 : // 110
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_DESVIACION.getOldValue()));
                break;
            }
            case 9 : // 9
            {
                value = (java.lang.Integer)(new Integer("2008"));
                break;
            }
            case 24 : // 24
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_COMPROMISO.getOldValue()));
                break;
            }
            case 93 : // 93
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)parameter_P3.getValue()).intValue()<=((java.lang.Double)field_CD_TIPOELEMENTO_05.getOldValue()).intValue()));
                break;
            }
            case 11 : // 11
            {
                value = (java.lang.String)(new String("A4"));
                break;
            }
            case 85 : // 85
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_ASIGANDO_04.getOldValue()));
                break;
            }
            case 81 : // 81
            {
                value = (java.lang.Object)(((java.lang.Double)field_CD_ELEMENTO_04.getOldValue()));
                break;
            }
            case 29 : // 29
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_COMPROMISO.getOldValue()));
                break;
            }
            case 47 : // 47
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_DESVIACION.getOldValue()));
                break;
            }
            case 72 : // 72
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_03.getOldValue()));
                break;
            }
            case 102 : // 102
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 0 : // 0
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 58 : // 58
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 67 : // 67
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_DESVIACION_02.getOldValue()));
                break;
            }
            case 55 : // 55
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PAGO_01.getOldValue()));
                break;
            }
            case 59 : // 59
            {
                value = (java.lang.Object)(((java.lang.Double)field_CD_ELEMENTO_02.getOldValue()));
                break;
            }
            case 82 : // 82
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)parameter_P3.getValue()).intValue()<=((java.lang.Double)field_CD_TIPOELEMENTO_04.getOldValue()).intValue()));
                break;
            }
            case 66 : // 66
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PAGO_02.getOldValue()));
                break;
            }
            case 88 : // 88
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PAGO_04.getOldValue()));
                break;
            }
            case 80 : // 80
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 20 : // 20
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_ASIGNADO.getOldValue()));
                break;
            }
            case 112 : // 112
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()));
                break;
            }
            case 64 : // 64
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_COMPROMISO_02.getOldValue()));
                break;
            }
            case 32 : // 32
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_GASTADO.getOldValue()));
                break;
            }
            case 77 : // 77
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PAGO_03.getOldValue()));
                break;
            }
            case 65 : // 65
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_GASTADO_02.getOldValue()));
                break;
            }
            case 103 : // 103
            {
                value = (java.lang.String)(java.util.Calendar.getInstance().get(java.util.Calendar.DATE)
+ "/" +
((java.util.Calendar.getInstance().get(java.util.Calendar.MONTH))+1)
+ "/" +
java.util.Calendar.getInstance().get(java.util.Calendar.YEAR));
                break;
            }
           default :
           {
               value = evaluateOld1(id);
           }
        }
        
        return value;
    }


    /**
     *
     */
    private Object evaluateOld1(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 30 : // 30
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_GASTADO.getOldValue()));
                break;
            }
            case 21 : // 21
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_ASIGNADO.getOldValue()));
                break;
            }
            case 90 : // 90
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 61 : // 61
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_02.getOldValue()));
                break;
            }
            case 96 : // 96
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_ASIGANDO_05.getOldValue()));
                break;
            }
            case 52 : // 52
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_ASIGANDO_01.getOldValue()));
                break;
            }
            case 46 : // 46
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_DESVIACION.getOldValue()));
                break;
            }
            case 2 : // 2
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 45 : // 45
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_DESVIACION.getOldValue()));
                break;
            }
            case 36 : // 36
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PAGO.getOldValue()));
                break;
            }
            case 89 : // 89
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_DESVIACION_04.getOldValue()));
                break;
            }
            case 78 : // 78
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_DESVIACION_03.getOldValue()));
                break;
            }
            case 42 : // 42
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_DESVIACION.getOldValue()));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 27 : // 27
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_COMPROMISO.getValue()));
                break;
            }
            case 98 : // 98
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_GASTADO_05.getEstimatedValue()));
                break;
            }
            case 34 : // 34
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_GASTADO.getValue()));
                break;
            }
            case 111 : // 111
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()));
                break;
            }
            case 26 : // 26
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_COMPROMISO.getValue()));
                break;
            }
            case 48 : // 48
            {
                value = (java.lang.Object)(((java.lang.Double)field_CD_ELEMENTO_01.getValue()));
                break;
            }
            case 49 : // 49
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)parameter_P3.getValue()).intValue()<=((java.lang.Double)field_CD_TIPOELEMENTO_01.getValue()).intValue()));
                break;
            }
            case 104 : // 104
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_06.getValue()));
                break;
            }
            case 40 : // 40
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PAGO.getValue()));
                break;
            }
            case 57 : // 57
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 31 : // 31
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_GASTADO.getValue()));
                break;
            }
            case 23 : // 23
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_ASIGNADO.getValue()));
                break;
            }
            case 109 : // 109
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PAGO.getValue()));
                break;
            }
            case 106 : // 106
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_ASIGNADO.getValue()));
                break;
            }
            case 13 : // 13
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PRESUPUESTO.getValue()));
                break;
            }
            case 62 : // 62
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PRESUPUESTO_02.getEstimatedValue()));
                break;
            }
            case 56 : // 56
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_DESVIACION_01.getEstimatedValue()));
                break;
            }
            case 60 : // 60
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)parameter_P3.getValue()).intValue()<=((java.lang.Double)field_CD_TIPOELEMENTO_02.getValue()).intValue()));
                break;
            }
            case 95 : // 95
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PRESUPUESTO_05.getEstimatedValue()));
                break;
            }
            case 16 : // 16
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PRESUPUESTO.getValue()));
                break;
            }
            case 100 : // 100
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_DESVIACION_05.getEstimatedValue()));
                break;
            }
            case 68 : // 68
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 99 : // 99
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PAGO_05.getEstimatedValue()));
                break;
            }
            case 22 : // 22
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_ASIGNADO.getValue()));
                break;
            }
            case 79 : // 79
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 33 : // 33
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_GASTADO.getValue()));
                break;
            }
            case 41 : // 41
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PAGO.getValue()));
                break;
            }
            case 50 : // 50
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_01.getValue()));
                break;
            }
            case 70 : // 70
            {
                value = (java.lang.Object)(((java.lang.Double)field_CD_ELEMENTO_03.getValue()));
                break;
            }
            case 107 : // 107
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_COMPROMISO.getValue()));
                break;
            }
            case 74 : // 74
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_ASIGANDO_03.getEstimatedValue()));
                break;
            }
            case 54 : // 54
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_GASTADO_01.getEstimatedValue()));
                break;
            }
            case 53 : // 53
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_COMPROMISO_01.getEstimatedValue()));
                break;
            }
            case 44 : // 44
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_DESVIACION.getValue()));
                break;
            }
            case 51 : // 51
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PRESUPUESTO_01.getEstimatedValue()));
                break;
            }
            case 38 : // 38
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PAGO.getValue()));
                break;
            }
            case 35 : // 35
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_GASTADO.getValue()));
                break;
            }
            case 8 : // 8
            {
                value = (java.lang.String)(new String("Admin"));
                break;
            }
            case 73 : // 73
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PRESUPUESTO_03.getEstimatedValue()));
                break;
            }
            case 83 : // 83
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_04.getValue()));
                break;
            }
            case 94 : // 94
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_05.getValue()));
                break;
            }
            case 97 : // 97
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_COMPROMISO_05.getEstimatedValue()));
                break;
            }
            case 15 : // 15
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PRESUPUESTO.getValue()));
                break;
            }
            case 12 : // 12
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PRESUPUESTO.getValue()));
                break;
            }
            case 3 : // 3
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 101 : // 101
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 108 : // 108
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_GASTADO.getValue()));
                break;
            }
            case 14 : // 14
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PRESUPUESTO.getValue()));
                break;
            }
            case 10 : // 10
            {
                value = (java.lang.Integer)(new Integer("2"));
                break;
            }
            case 18 : // 18
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_ASIGNADO.getValue()));
                break;
            }
            case 19 : // 19
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_ASIGNADO.getValue()));
                break;
            }
            case 7 : // 7
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 91 : // 91
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 86 : // 86
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_COMPROMISO_04.getEstimatedValue()));
                break;
            }
            case 76 : // 76
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_GASTADO_03.getEstimatedValue()));
                break;
            }
            case 17 : // 17
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PRESUPUESTO.getValue()));
                break;
            }
            case 43 : // 43
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_DESVIACION.getValue()));
                break;
            }
            case 92 : // 92
            {
                value = (java.lang.Object)(((java.lang.Double)field_CD_ELEMENTO_05.getValue()));
                break;
            }
            case 1 : // 1
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 63 : // 63
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_ASIGANDO_02.getEstimatedValue()));
                break;
            }
            case 28 : // 28
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_COMPROMISO.getValue()));
                break;
            }
            case 75 : // 75
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_COMPROMISO_03.getEstimatedValue()));
                break;
            }
            case 105 : // 105
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PRESUPUESTO.getValue()));
                break;
            }
            case 39 : // 39
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PAGO.getValue()));
                break;
            }
            case 69 : // 69
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 37 : // 37
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PAGO.getValue()));
                break;
            }
            case 87 : // 87
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_GASTADO_04.getEstimatedValue()));
                break;
            }
            case 4 : // 4
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 6 : // 6
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 71 : // 71
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)parameter_P3.getValue()).intValue()<=((java.lang.Double)field_CD_TIPOELEMENTO_03.getValue()).intValue()));
                break;
            }
            case 84 : // 84
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PRESUPUESTO_04.getEstimatedValue()));
                break;
            }
            case 25 : // 25
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_COMPROMISO.getValue()));
                break;
            }
            case 5 : // 5
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 110 : // 110
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_DESVIACION.getValue()));
                break;
            }
            case 9 : // 9
            {
                value = (java.lang.Integer)(new Integer("2008"));
                break;
            }
            case 24 : // 24
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_COMPROMISO.getValue()));
                break;
            }
            case 93 : // 93
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)parameter_P3.getValue()).intValue()<=((java.lang.Double)field_CD_TIPOELEMENTO_05.getValue()).intValue()));
                break;
            }
            case 11 : // 11
            {
                value = (java.lang.String)(new String("A4"));
                break;
            }
            case 85 : // 85
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_ASIGANDO_04.getEstimatedValue()));
                break;
            }
            case 81 : // 81
            {
                value = (java.lang.Object)(((java.lang.Double)field_CD_ELEMENTO_04.getValue()));
                break;
            }
            case 29 : // 29
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_COMPROMISO.getValue()));
                break;
            }
            case 47 : // 47
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_DESVIACION.getValue()));
                break;
            }
            case 72 : // 72
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_03.getValue()));
                break;
            }
            case 102 : // 102
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 0 : // 0
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 58 : // 58
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 67 : // 67
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_DESVIACION_02.getEstimatedValue()));
                break;
            }
            case 55 : // 55
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PAGO_01.getEstimatedValue()));
                break;
            }
            case 59 : // 59
            {
                value = (java.lang.Object)(((java.lang.Double)field_CD_ELEMENTO_02.getValue()));
                break;
            }
            case 82 : // 82
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)parameter_P3.getValue()).intValue()<=((java.lang.Double)field_CD_TIPOELEMENTO_04.getValue()).intValue()));
                break;
            }
            case 66 : // 66
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PAGO_02.getEstimatedValue()));
                break;
            }
            case 88 : // 88
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PAGO_04.getEstimatedValue()));
                break;
            }
            case 80 : // 80
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 20 : // 20
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_ASIGNADO.getValue()));
                break;
            }
            case 112 : // 112
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()));
                break;
            }
            case 64 : // 64
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_COMPROMISO_02.getEstimatedValue()));
                break;
            }
            case 32 : // 32
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_GASTADO.getValue()));
                break;
            }
            case 77 : // 77
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_PAGO_03.getEstimatedValue()));
                break;
            }
            case 65 : // 65
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_GASTADO_02.getEstimatedValue()));
                break;
            }
            case 103 : // 103
            {
                value = (java.lang.String)(java.util.Calendar.getInstance().get(java.util.Calendar.DATE)
+ "/" +
((java.util.Calendar.getInstance().get(java.util.Calendar.MONTH))+1)
+ "/" +
java.util.Calendar.getInstance().get(java.util.Calendar.YEAR));
                break;
            }
           default :
           {
               value = evaluateEstimated1(id);
           }
        }
        
        return value;
    }


    /**
     *
     */
    private Object evaluateEstimated1(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 30 : // 30
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_GASTADO.getValue()));
                break;
            }
            case 21 : // 21
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_ASIGNADO.getValue()));
                break;
            }
            case 90 : // 90
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 61 : // 61
            {
                value = (java.lang.String)(((java.lang.String)field_DS_ELEMENTO_02.getValue()));
                break;
            }
            case 96 : // 96
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_ASIGANDO_05.getEstimatedValue()));
                break;
            }
            case 52 : // 52
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_ASIGANDO_01.getEstimatedValue()));
                break;
            }
            case 46 : // 46
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_DESVIACION.getValue()));
                break;
            }
            case 2 : // 2
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 45 : // 45
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_DESVIACION.getValue()));
                break;
            }
            case 36 : // 36
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_PAGO.getValue()));
                break;
            }
            case 89 : // 89
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_DESVIACION_04.getEstimatedValue()));
                break;
            }
            case 78 : // 78
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_IMP_DESVIACION_03.getEstimatedValue()));
                break;
            }
            case 42 : // 42
            {
                value = (java.lang.Double)(((java.lang.Double)field_IMP_DESVIACION.getValue()));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
