/*
 * Generated by JasperReports - 2/09/08 13:42
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;

import java.util.*;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.data.*;


/**
 *
 */
public class rpt_LibrosSort46 extends JRCalculator
{


    /**
     *
     */
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillParameter parameter_P1 = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_P2 = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillParameter parameter_P3 = null;
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;

    private JRFillField field_CD_SORTEO = null;
    private JRFillField field_FENVIO = null;
    private JRFillField field_NOFRECIDOS = null;
    private JRFillField field_DS_SORTEO = null;
    private JRFillField field_PARTICIPANTES = null;
    private JRFillField field_FSORTEO = null;
    private JRFillField field_PREGUNTA = null;
    private JRFillField field_CD_MATERIA = null;
    private JRFillField field_ACERTANTES = null;
    private JRFillField field_MATERIA = null;
    private JRFillField field_NENVIADOS = null;
    private JRFillField field_CODIGO = null;
    private JRFillField field_RESPUESTA = null;
    private JRFillField field_TITULO = null;

    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_TPARTICIPANTES = null;
    private JRFillVariable variable_TACERTANTES = null;
    private JRFillVariable variable_TENVIADOS = null;
    private JRFillVariable variable_TOFRECIDOS = null;
    private JRFillVariable variable_STOFRECIDOS = null;
    private JRFillVariable variable_TTENVIADOS = null;
    private JRFillVariable variable_STTOFRECIDOS = null;
    private JRFillVariable variable_STACERTANTES = null;
    private JRFillVariable variable_STPARTICIPANTES = null;
    private JRFillVariable variable_sorteo_COUNT = null;
    private JRFillVariable variable_libro_COUNT = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
        parameter_P1 = (JRFillParameter)pm.get("P1");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_P2 = (JRFillParameter)pm.get("P2");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
        parameter_P3 = (JRFillParameter)pm.get("P3");
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
        field_CD_SORTEO = (JRFillField)fm.get("CD_SORTEO");
        field_FENVIO = (JRFillField)fm.get("FENVIO");
        field_NOFRECIDOS = (JRFillField)fm.get("NOFRECIDOS");
        field_DS_SORTEO = (JRFillField)fm.get("DS_SORTEO");
        field_PARTICIPANTES = (JRFillField)fm.get("PARTICIPANTES");
        field_FSORTEO = (JRFillField)fm.get("FSORTEO");
        field_PREGUNTA = (JRFillField)fm.get("PREGUNTA");
        field_CD_MATERIA = (JRFillField)fm.get("CD_MATERIA");
        field_ACERTANTES = (JRFillField)fm.get("ACERTANTES");
        field_MATERIA = (JRFillField)fm.get("MATERIA");
        field_NENVIADOS = (JRFillField)fm.get("NENVIADOS");
        field_CODIGO = (JRFillField)fm.get("CODIGO");
        field_RESPUESTA = (JRFillField)fm.get("RESPUESTA");
        field_TITULO = (JRFillField)fm.get("TITULO");
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
        variable_TPARTICIPANTES = (JRFillVariable)vm.get("TPARTICIPANTES");
        variable_TACERTANTES = (JRFillVariable)vm.get("TACERTANTES");
        variable_TENVIADOS = (JRFillVariable)vm.get("TENVIADOS");
        variable_TOFRECIDOS = (JRFillVariable)vm.get("TOFRECIDOS");
        variable_STOFRECIDOS = (JRFillVariable)vm.get("STOFRECIDOS");
        variable_TTENVIADOS = (JRFillVariable)vm.get("TTENVIADOS");
        variable_STTOFRECIDOS = (JRFillVariable)vm.get("STTOFRECIDOS");
        variable_STACERTANTES = (JRFillVariable)vm.get("STACERTANTES");
        variable_STPARTICIPANTES = (JRFillVariable)vm.get("STPARTICIPANTES");
        variable_sorteo_COUNT = (JRFillVariable)vm.get("sorteo_COUNT");
        variable_libro_COUNT = (JRFillVariable)vm.get("libro_COUNT");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 85 : // 85
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_ACERTANTES.getValue()));
                break;
            }
            case 59 : // 59
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_PARTICIPANTES.getValue()));
                break;
            }
            case 55 : // 55
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 84 : // 84
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_PARTICIPANTES.getValue()));
                break;
            }
            case 82 : // 82
            {
                value = (java.lang.String)(((java.lang.String)field_FSORTEO.getValue()));
                break;
            }
            case 57 : // 57
            {
                value = (java.lang.String)("01/01/3000");
                break;
            }
            case 68 : // 68
            {
                value = (java.lang.Object)(((java.lang.Integer)field_CD_SORTEO.getValue()));
                break;
            }
            case 83 : // 83
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_NOFRECIDOS.getValue()));
                break;
            }
            case 51 : // 51
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 61 : // 61
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_NENVIADOS.getValue()));
                break;
            }
            case 75 : // 75
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 93 : // 93
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_STACERTANTES.getValue()));
                break;
            }
            case 80 : // 80
            {
                value = (java.lang.String)(((java.lang.String)field_TITULO.getValue()));
                break;
            }
            case 79 : // 79
            {
                value = (java.lang.String)(((java.lang.String)field_CODIGO.getValue()));
                break;
            }
            case 81 : // 81
            {
                value = (java.lang.String)(((java.lang.String)field_MATERIA.getValue()));
                break;
            }
            case 78 : // 78
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 48 : // 48
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 91 : // 91
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getValue()));
                break;
            }
            case 67 : // 67
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_TPARTICIPANTES.getValue()));
                break;
            }
            case 66 : // 66
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_TACERTANTES.getValue()));
                break;
            }
            case 86 : // 86
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_NENVIADOS.getValue()));
                break;
            }
            case 73 : // 73
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_STOFRECIDOS.getValue()));
                break;
            }
            case 90 : // 90
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getValue()));
                break;
            }
            case 54 : // 54
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 69 : // 69
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_PARTICIPANTES.getValue()));
                break;
            }
            case 56 : // 56
            {
                value = (java.lang.String)("01/01/1900");
                break;
            }
            case 60 : // 60
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_ACERTANTES.getValue()));
                break;
            }
            case 50 : // 50
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 62 : // 62
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_NOFRECIDOS.getValue()));
                break;
            }
            case 88 : // 88
            {
                value = (java.lang.String)(((java.lang.String)field_PREGUNTA.getValue()));
                break;
            }
            case 65 : // 65
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_STOFRECIDOS.getValue()));
                break;
            }
            case 53 : // 53
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 58 : // 58
            {
                value = (java.lang.String)("");
                break;
            }
            case 94 : // 94
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_TTENVIADOS.getValue()));
                break;
            }
            case 71 : // 71
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_TENVIADOS.getValue()));
                break;
            }
            case 89 : // 89
            {
                value = (java.lang.String)(((java.lang.String)field_RESPUESTA.getValue()));
                break;
            }
            case 74 : // 74
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 76 : // 76
            {
                value = (java.lang.Object)(((java.lang.String)field_CODIGO.getValue()));
                break;
            }
            case 72 : // 72
            {
                value = (java.lang.String)(((java.lang.String)field_DS_SORTEO.getValue()));
                break;
            }
            case 70 : // 70
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_ACERTANTES.getValue()));
                break;
            }
            case 52 : // 52
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 87 : // 87
            {
                value = (java.lang.String)(((java.lang.String)field_FENVIO.getValue()));
                break;
            }
            case 63 : // 63
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_TOFRECIDOS.getValue()));
                break;
            }
            case 92 : // 92
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_STPARTICIPANTES.getValue()));
                break;
            }
            case 95 : // 95
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_STTOFRECIDOS.getValue()));
                break;
            }
            case 49 : // 49
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 77 : // 77
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 64 : // 64
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_NENVIADOS.getValue()));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 85 : // 85
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_ACERTANTES.getOldValue()));
                break;
            }
            case 59 : // 59
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_PARTICIPANTES.getOldValue()));
                break;
            }
            case 55 : // 55
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 84 : // 84
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_PARTICIPANTES.getOldValue()));
                break;
            }
            case 82 : // 82
            {
                value = (java.lang.String)(((java.lang.String)field_FSORTEO.getOldValue()));
                break;
            }
            case 57 : // 57
            {
                value = (java.lang.String)("01/01/3000");
                break;
            }
            case 68 : // 68
            {
                value = (java.lang.Object)(((java.lang.Integer)field_CD_SORTEO.getOldValue()));
                break;
            }
            case 83 : // 83
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_NOFRECIDOS.getOldValue()));
                break;
            }
            case 51 : // 51
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 61 : // 61
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_NENVIADOS.getOldValue()));
                break;
            }
            case 75 : // 75
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 93 : // 93
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_STACERTANTES.getOldValue()));
                break;
            }
            case 80 : // 80
            {
                value = (java.lang.String)(((java.lang.String)field_TITULO.getOldValue()));
                break;
            }
            case 79 : // 79
            {
                value = (java.lang.String)(((java.lang.String)field_CODIGO.getOldValue()));
                break;
            }
            case 81 : // 81
            {
                value = (java.lang.String)(((java.lang.String)field_MATERIA.getOldValue()));
                break;
            }
            case 78 : // 78
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 48 : // 48
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 91 : // 91
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()));
                break;
            }
            case 67 : // 67
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_TPARTICIPANTES.getOldValue()));
                break;
            }
            case 66 : // 66
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_TACERTANTES.getOldValue()));
                break;
            }
            case 86 : // 86
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_NENVIADOS.getOldValue()));
                break;
            }
            case 73 : // 73
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_STOFRECIDOS.getOldValue()));
                break;
            }
            case 90 : // 90
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()));
                break;
            }
            case 54 : // 54
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 69 : // 69
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_PARTICIPANTES.getOldValue()));
                break;
            }
            case 56 : // 56
            {
                value = (java.lang.String)("01/01/1900");
                break;
            }
            case 60 : // 60
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_ACERTANTES.getOldValue()));
                break;
            }
            case 50 : // 50
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 62 : // 62
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_NOFRECIDOS.getOldValue()));
                break;
            }
            case 88 : // 88
            {
                value = (java.lang.String)(((java.lang.String)field_PREGUNTA.getOldValue()));
                break;
            }
            case 65 : // 65
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_STOFRECIDOS.getOldValue()));
                break;
            }
            case 53 : // 53
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 58 : // 58
            {
                value = (java.lang.String)("");
                break;
            }
            case 94 : // 94
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_TTENVIADOS.getOldValue()));
                break;
            }
            case 71 : // 71
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_TENVIADOS.getOldValue()));
                break;
            }
            case 89 : // 89
            {
                value = (java.lang.String)(((java.lang.String)field_RESPUESTA.getOldValue()));
                break;
            }
            case 74 : // 74
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 76 : // 76
            {
                value = (java.lang.Object)(((java.lang.String)field_CODIGO.getOldValue()));
                break;
            }
            case 72 : // 72
            {
                value = (java.lang.String)(((java.lang.String)field_DS_SORTEO.getOldValue()));
                break;
            }
            case 70 : // 70
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_ACERTANTES.getOldValue()));
                break;
            }
            case 52 : // 52
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 87 : // 87
            {
                value = (java.lang.String)(((java.lang.String)field_FENVIO.getOldValue()));
                break;
            }
            case 63 : // 63
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_TOFRECIDOS.getOldValue()));
                break;
            }
            case 92 : // 92
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_STPARTICIPANTES.getOldValue()));
                break;
            }
            case 95 : // 95
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_STTOFRECIDOS.getOldValue()));
                break;
            }
            case 49 : // 49
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 77 : // 77
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 64 : // 64
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_NENVIADOS.getOldValue()));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 85 : // 85
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_ACERTANTES.getValue()));
                break;
            }
            case 59 : // 59
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_PARTICIPANTES.getValue()));
                break;
            }
            case 55 : // 55
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 84 : // 84
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_PARTICIPANTES.getValue()));
                break;
            }
            case 82 : // 82
            {
                value = (java.lang.String)(((java.lang.String)field_FSORTEO.getValue()));
                break;
            }
            case 57 : // 57
            {
                value = (java.lang.String)("01/01/3000");
                break;
            }
            case 68 : // 68
            {
                value = (java.lang.Object)(((java.lang.Integer)field_CD_SORTEO.getValue()));
                break;
            }
            case 83 : // 83
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_NOFRECIDOS.getValue()));
                break;
            }
            case 51 : // 51
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 61 : // 61
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_NENVIADOS.getValue()));
                break;
            }
            case 75 : // 75
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 93 : // 93
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_STACERTANTES.getEstimatedValue()));
                break;
            }
            case 80 : // 80
            {
                value = (java.lang.String)(((java.lang.String)field_TITULO.getValue()));
                break;
            }
            case 79 : // 79
            {
                value = (java.lang.String)(((java.lang.String)field_CODIGO.getValue()));
                break;
            }
            case 81 : // 81
            {
                value = (java.lang.String)(((java.lang.String)field_MATERIA.getValue()));
                break;
            }
            case 78 : // 78
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 48 : // 48
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 91 : // 91
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()));
                break;
            }
            case 67 : // 67
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_TPARTICIPANTES.getEstimatedValue()));
                break;
            }
            case 66 : // 66
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_TACERTANTES.getEstimatedValue()));
                break;
            }
            case 86 : // 86
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_NENVIADOS.getValue()));
                break;
            }
            case 73 : // 73
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_STOFRECIDOS.getEstimatedValue()));
                break;
            }
            case 90 : // 90
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()));
                break;
            }
            case 54 : // 54
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 69 : // 69
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_PARTICIPANTES.getValue()));
                break;
            }
            case 56 : // 56
            {
                value = (java.lang.String)("01/01/1900");
                break;
            }
            case 60 : // 60
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_ACERTANTES.getValue()));
                break;
            }
            case 50 : // 50
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 62 : // 62
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_NOFRECIDOS.getValue()));
                break;
            }
            case 88 : // 88
            {
                value = (java.lang.String)(((java.lang.String)field_PREGUNTA.getValue()));
                break;
            }
            case 65 : // 65
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_STOFRECIDOS.getEstimatedValue()));
                break;
            }
            case 53 : // 53
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 58 : // 58
            {
                value = (java.lang.String)("");
                break;
            }
            case 94 : // 94
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_TTENVIADOS.getEstimatedValue()));
                break;
            }
            case 71 : // 71
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_TENVIADOS.getEstimatedValue()));
                break;
            }
            case 89 : // 89
            {
                value = (java.lang.String)(((java.lang.String)field_RESPUESTA.getValue()));
                break;
            }
            case 74 : // 74
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 76 : // 76
            {
                value = (java.lang.Object)(((java.lang.String)field_CODIGO.getValue()));
                break;
            }
            case 72 : // 72
            {
                value = (java.lang.String)(((java.lang.String)field_DS_SORTEO.getValue()));
                break;
            }
            case 70 : // 70
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_ACERTANTES.getValue()));
                break;
            }
            case 52 : // 52
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 87 : // 87
            {
                value = (java.lang.String)(((java.lang.String)field_FENVIO.getValue()));
                break;
            }
            case 63 : // 63
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_TOFRECIDOS.getEstimatedValue()));
                break;
            }
            case 92 : // 92
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_STPARTICIPANTES.getEstimatedValue()));
                break;
            }
            case 95 : // 95
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_STTOFRECIDOS.getEstimatedValue()));
                break;
            }
            case 49 : // 49
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 77 : // 77
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 64 : // 64
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_NENVIADOS.getValue()));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
